# Instrumental Variables

This chapter builds upon Chapter 12 of @Hansen2022. 


## Introduction

The concepts of **endogeneity** and **instrumental variable** are fundamental to econometrics, and mark a substantial departure from other branches of statistics. 

The ideas of endogeneity arise naturally in economics from models of simultaneous equations, most notably the classic supply/demand model of price determination.

<!-- ### Overview {-} -->

We say that there is **endogeneity** in the linear model
$$
\begin{align}
  Y_i=X_i'\beta+\varepsilon_i
\end{align}
$${#eq-IVLinMod}
if $\beta$ is the parameter of interest and if $E(\varepsilon_i|X_i)\neq 0$ and thus
$$
E(X_i\varepsilon_i)\neq 0.
$${#eq-endogen}
When @eq-endogen holds, $X$ is **endogenous** for $\beta.$

This situation constitutes a core problem in econometrics which is not so much in the focus of the statistics literature. 


Equation @eq-IVLinMod is called a **structural equation** and $\beta$ a **structural parameter** and it is important to distinguish @eq-IVLinMod from the regression/projection models we considered so far. It may be the case that a structural model coincides with a regression/projector model, but this is not necessarily the case.


Endogeneity **cannot** happen if the coefficient is defined by a linear projection. We can *define*[^1] the linear (population) projection coefficient 
$$
\beta^*=E(X_iX_i')^{-1}E(X_iY)
$$
and the corresponding linear (population) projection equation
$$
Y_i = X_i'\beta^* + \varepsilon_i^*,
$$ 
where then, by construction (projection properties), 
$$
E(X_i\varepsilon_i^*)=0
$$

[^1]: Caution, here we simply define $\beta^*$ as $\beta^*=E(X_iX_i')^{-1}E(X_iY)$ which results the population projection coefficient for the population projection of $Y$ into the space spanned by $X_i$. We did not derive the expression for $\beta^*$ using the exogeneity assumption as we did in @sec-MMEstimator; indeed, the exogeneity assumption may be violated.


The (population) projection coefficient $\beta^*$ and the structural parameter $\beta$ coincide ($\beta^*=\beta$) under exogeneity. However, under endogeneity (@eq-endogen) the projection coefficient $\beta^*$ does not equal the structural parameter
$$
\begin{align*}
\beta^* & =E(X_iX_i')^{-1}E(X_iY)\\
\beta^* & =E(X_iX_i')^{-1}E(X_i (X_i'\beta + \varepsilon_i) )\\
%\beta^* & =E(X_iX_i')^{-1}E(X_i X_i') \beta + 
%            E(X_iX_i')^{-1}E(X_i\varepsilon_i)\\
\beta^* & = \beta + E(X_iX_i')^{-1}\underbrace{E(X_i \varepsilon_i)}_{\neq 0}\neq \beta\\
\end{align*}
$$


Thus under endogeneity we cannot simply use the projection coefficient to derive an estimator since the projection coefficient does not identify the structural parameter of interest. 

That is, endogeneity implies that the least squares estimator is inconsistent for the structural parameter. Indeed, under i.i.d. sampling, least squares is consistent for the projection coefficient.
$$
\hat\beta\to_pE(X_iX_i')^{-1}E(X_iY) = \beta^* \neq \beta.
$$

But since the structural parameter $\beta$ is here the parameter of interest, endogeneity requires the development of alternative estimation methods. 


## Examples for Structural Models 

The structural model approach in econometrics goes back to the seminal paper *The probability approach in econometrics* by @Haavelmo1944. 


Under the structural approach one, first, specifies a probabilistic economic model (taking into account economic theory), and then performs a quantitative analysis under the assumption that the economic model is correctly specified. This approach is reflected by Assumption 1 in  @sec-MLR. Researchers often describe this as “taking their model seriously”. A criticism of the structural approach is that it is misleading to treat an economic model as correctly specified. Rather, it is more accurate to view a model as a useful abstraction or approximation.


::: {#exm-MeasurementError}

## Measurement error in the regressor 

<br>

Suppose that:

* $(Y_i,Z_i)$ is a multivariate random variable i.i.d. across $i=1,\dots,n$ 
* $E(Y_i|Z_i)=Z_i'\beta$
* $\beta$ is the structural parameter
* $Y_i  = Z_i'\beta + \varepsilon_i$ is the structural equation for which our model assumptions of @sec-LinModAssumptions can be justified.

Unfortunately, $Z_i$ is not observed (latent), instead we observe a noisy version of $Z_i$
$$
X_i=Z_i + u_i,
$$
where $u_i$ is a $(K\times 1)$ dimensional **classic measurement error**, i.e.

* $u_i$ is independent of all other stochastic quantities in the model
* $E(u_i)=0$

such that $X_i$ is a noisy, but unbiased measure of $Z_i.$

It's easy to express $Y_i$ as a function of the observable $X_i$
$$
\begin{align*}
Y_i 
& = Z_i'\beta + \varepsilon_i \\ 
& = (X_i - u_i)'\beta + \varepsilon_i \\ 
& = X_i'\beta  + v,\\ 
\end{align*}
$$
where $v_i=\varepsilon_i - u_i'\beta$. 

That is, the relationship of $Y_i$ and $X_i$ is described by a linear equation
$$
Y_i = X_i'\beta  + v_i,
$$
with a stochastic error term $v_i$, but this error term is (generally) not a projection error since
$$
\begin{align}
E(X_iv_i) 
& = E((Z_i + u_i)\,(\varepsilon_i - u_i'\beta)) \\
& = \underbrace{E(Z_i \varepsilon_i)}_{=0} - \underbrace{E(Z_iu_i'\beta)}_{=0}  + \underbrace{E(u_i \varepsilon_i)}_{=0} - E(u_iu_i')\beta \\
& = - E(u_iu_i')\beta \\ 
&\neq 0 
\end{align}
$${#eq-measurementBias2}
if $\beta\neq 0$ and $E(u_iu_i')\neq 0,$ where generally 

* $\beta$ will not equal zero and 
* the $(K\times K)$ variance-covariance matrix $E(u_iu_i')$ will also not equal a zero matrix since this would mean that the measurement errors have variance zero.


We can calculate the (population) projection coefficient $\beta^*$ (which can be consistently estimated): 
$$
\begin{align*}
\beta^* 
& = E(X_iX_i')^{-1} E(X_i Y_i)\\
& = E(X_iX_i')^{-1} E(X_i (X_i'\beta + v_i))\\
& = \beta + E(X_iX_i')^{-1} \underbrace{E(X_i v_i)}_{\neq 0}
\end{align*}
$$
In the special case where $K=1$, we have
$$
\begin{align}
\beta^*_1 
& = \beta_1 + \frac{E(X_i v_i)}{E(X_i^2)}\\
& = \beta_1 - \frac{E(u_i^2)\beta_1}{E(X_i^2)}\\
& = \beta_1\left(1 - \frac{ E(u_i^2)}{E(X_i^2)}\right),
\end{align}
$${#eq-measurementBias}
where, by @eq-measurementBias2, $E(X_iv_i)=-E(u_i^2)\beta_1$, and 
where the inequality follows from observing that $E(u_i^2)/E(X_i^2)<1$ since
$$
\begin{align*}
E(X_i^2) 
&= E((Z_i + u_i)^2)\\
&= E(Z_i^2) + 2E(Z_iu_i) + E(u_i^2) \\
&= E(Z_i^2) + 0 + E(u_i^2)\\  
&> E(u_i^2)\\  
\Leftrightarrow\quad \frac{E(u_i^2)}{E(X_i^2)}&<1.
\end{align*}
$$
@eq-measurementBias shows that projection coefficient $\beta_1^*$ shrinks the structural parameter $\beta_1$ towards zero. This is called  **measurement error bias** or **attenuation bias**.
:::


::: {#exm-SupplyAndDemand}

##  Supply and Demand

<br>


The variables $Q$ and $P$ (Quantity and Price) are determined jointly by the following simultaneous equation system consisting of the demand equation
$$
Q_i = -\beta_1 P_i + \varepsilon_{1i}
$$
and of the supply equation
$$
Q_i =  \beta_2 P_i + \varepsilon_{2i},
$$
where we assume that $Q_i$ and $P_i$ are centered such that we can drop the intercepts. 

Assume that the $(2\times 1)$ dimensional joint random error $\varepsilon_i=(\varepsilon_{1i},\varepsilon_{2i})'$ satisfies $E(\varepsilon)=0$ and $E(\varepsilon\varepsilon')=I_2$ (the latter for simplicity). 

> What happens if we regress $Q_i$ on $P_i$? 

To answer this question, we need to solve $Q_i$ and $P_i$ in terms of the errors $\varepsilon_{1i}$ and $\varepsilon_{2i}$.
$$
\left(\begin{matrix}
1 & \beta_1\\
1 & -\beta_2\\
\end{matrix}
\right)
\left(\begin{matrix}
Q_i\\
P_i\\
\end{matrix}
\right) = 
\left(\begin{matrix}
e_{1i}\\
e_{2i}\\
\end{matrix}
\right)
$$
Rewriting yields (assuming invertibility)
$$
\begin{align}
\left(\begin{matrix}
Q_i\\
P_i\\
\end{matrix}
\right) 
&= 
\left(\begin{matrix}
1 & \beta_1\\
1 & -\beta_2\\
\end{matrix}
\right)^{-1}
\left(\begin{matrix}
e_{1i}\\
e_{2i}\\
\end{matrix}
\right)\\[2ex]
&= 
\frac{1}{-\beta_2 - \beta_1}
\left(\begin{matrix}
-\beta_2 &   -\beta_1\\
 - 1    &           1\\
\end{matrix}
\right)
\left(\begin{matrix}
e_{1i}\\
e_{2i}\\
\end{matrix}
\right)\\[2ex]
&= 
\left(\begin{matrix}
\beta_2 &   \beta_1\\
 1    &     -1\\
\end{matrix}\right)
\left(\begin{matrix}
e_{1i}\\
e_{2i}\\
\end{matrix}\right)
\frac{1}{\beta_1 +\beta_2}\\[2ex]
&=
\left(
\begin{matrix}
(\beta_2 e_{1i} + \beta_1  e_{2i})/(\beta_1 + \beta_2)\\
(e_{1i} - e_{2i})/(\beta_1 + \beta_2)
\end{matrix}  
\right)
\end{align}
$$
Thus
$$
\begin{align*}
E(P_iQ_i)
&=\frac{E\left((e_{1i} - e_{2i})(\beta_2 e_{1i} + \beta_1  e_{2i})\right)}{(\beta_1 + \beta_2)^2}\\ 
&=\frac{\beta_2 E\left(e_{1i}^2\right) - \beta_1 E\left(e_{2i}^2\right)}{(\beta_1 + \beta_2)^2}=\frac{\beta_2 - \beta_1}{(\beta_1 + \beta_2)^2}
\end{align*}
$$
$$
\begin{align*}
E(P_i^2)
&=\frac{E\left((e_{1i} - e_{2i})^2\right)}{(\beta_1 + \beta_2)^2}\\ 
&=\frac{E\left(e_{1i}^2\right) + E\left(e_{2i}^2\right)}{(\beta_1 + \beta_2)^2} = \frac{2}{(\beta_1 + \beta_2)^2}
\end{align*}
$$

The (population) projection of $Q_i$ on $P_i$ yield 
$$
Q_i=\beta^* P_i+\varepsilon^*_i
$$ 
with $E(P_i\varepsilon^*_i)=0$ and 
$$
\beta^* = \frac{E(P_iQ_i)}{E(P^2)} = \frac{\beta_2 - \beta_1}{2}
$$
The projection coefficient equals the average of the demand slope $\beta_1$ and the supply slope $\beta_2.$ The OLS estimator satisfies $\hat\beta\to_p\beta^*$ and thus the limit does not equal on of the structural parameters $\beta_1$ or $\beta_2.$ This is called **simultaneous equation bias**.  

Generally, when both the dependent variable and a regressor are **simultaneously determined** then the regressor should be treated as endogenous.
:::


## Endogenous Regressors

Technically, we say that a regressor $X_i$ is **exogenous** for $\beta$ if $E(X_i\varepsilon_i)=0.$ In general the distinction in an economic model is that a regressor $X_i$ is endogenous if it is jointly determined with $Y_i,$ while a regressor $X_i$ is exogenous if it is determined separately from $Y_i.$ 

Usually, only a subset of the regressors need to be treated as endogenous. In the following, we partition the vector of regressors 
$$
X_i*=(\underbrace{X_{i1}'}_{(1\times K_1)}, \underbrace{Y_{i2}'}_{(1\times K_2)}),
$$ 
with $K=K_1 + K_2$, and with: 

* Exogenous variables denoted as $X_{i1}$ 
* Endogenous variables denoted as $Y_{i2}$ in analogy to the (always) endogenous dependent variable $Y_i$ 
* The dependent variable is renamed as $Y_i\equiv Y_{i1}$ 

(Be aware that $X_{i1}$ is here a $(K_1\times 1)$ dimensional random vector.)

The structural equation is then
$$
Y_{i1}=X_{i1}'\beta_1 + Y_{i2}'\beta_2 + \varepsilon_i
$${#eq-StructuralEqEndogen1}  
This notation clarifies which variables are exogenous and which endogenous:

* $X_{i1}$: Exogenous regressors, i.e. $E(X_{i1}\varepsilon_i)=0$
* $Y_{i2}$: Endogenous regressors, i.e. $E(Y_{i2}\varepsilon_i)\neq 0$
* $Y_{i1}$: Endogenous dependent variable, i.e. $E(Y_{i1}\varepsilon_i)\neq 0$

## Instruments

To consistently estimate the structural parameter $\beta$ we need additional information. One type of information commonly used in econometrics are called **instruments**.


::: {#def-InstrumentalVariable}

## Instrumental Variable

The $\ell\times 1$ random vector $Z_i$ is called an **instrumental variable** for @eq-StructuralEqEndogen1 if
$$
E(Z_i\varepsilon_i)=0
$${#eq-IV1}
$$
\operatorname{rank}\Big(E(Z_iZ_i')\Big)=\ell  
$${#eq-IV2}
$$
\operatorname{rank}\Big(\underbrace{E(Z_iX_i')}_{(\ell\times K)}\Big)=K, 
$${#eq-IV3}
where $X_i'=(X_{i1}',Y_{i2}').$
:::

**Explanation of @def-InstrumentalVariable:**

* @eq-IV1 states that the instruments are uncorrelated with the error term (**exogeneity condition**)
* @eq-IV2 excludes linearly redundant instrument instruments
* @eq-IV3 is called the **relevance condition** and is essential for the
identification of the model, as we discuss later. 
  * A necessary condition for @eq-IV3 is that $\ell\geq K.$


Note that the exogenous regressors $X_{i1}$ fulfill @eq-IV1 and thus should be included as (additional) instrumental variables, i.e. 
$$
Z_i=
\underbrace{\left(\begin{matrix}Z_{i1}\\Z_{i2}\end{matrix}\right)}_{((\ell + K_1)\times 1)}=
\underbrace{\left(\begin{matrix}X_{i1}\\Z_{i2}\end{matrix}\right)}_{((\ell + K_1)\times 1)}
$$

* $Z_{i1}$: ($K_1$ many) **included exogenous variables**:
  * uncorrelated with $\varepsilon_i$ and thus potentially usable
  * included since they have potentially non-zero coefficients in the equation for $Y_i$ 
* $Z_{i2}$: ($\ell$ many) **excluded exogenous variables**:
  * uncorrelated with $\varepsilon_i$  and thus potentially usable
  * excluded since they have **zero coefficients**[^1] in the equation for $Y_i$

[^1]: The instrumental variables $Z_{i2}$ correlate with $Y_i$ only indirectly, because they correlate with $X_{i1}$ (by @eq-IV3). Therefore, since $X_{i1}$ are included in the equation for $Y_i$, there are no variations left in $Y_i$ that correlate with $Z_{i2}.$ Thus the instrumental variables $Z_{i2}$ have zero coefficients in the equation for $Y_i.$


With this notation we can also write the structural @eq-StructuralEqEndogen1 as
$$
Y_{i1} = Z_{i1}'\beta_1 + Y_{i2}'\beta_2 + \varepsilon_i
$${#eq-StructuralEqEndogen2}


**Terminology:**

* $Z_{i1}$: The *exogenous regressors* ($Z_{i1}=X_{i1}$)
* $Y_{i2}$: The *endogenous regressor*
* $Z_{i2}$: The *instrumental variables*


We say that the model is 

  * **just-identified** if $\ell = K$ 
  * **over-identified** if $\ell > K$


> What variables can be used as Instrumental Variables (IVs)? 

1. Instrumental variables must be uncorrelated with the error term (@eq-IV1).
2. Instrumental variables must be correlated with the endogenous variables $Y_{i2}$ also after controlling for the other already included exogenous variables $Z_{i1}$ (@eq-IV3).[^1] (I.e. the IVs must contain additional information, and thus must not be a perfect multicollinearity between the IVs $Z_{i2}$ and with the already included exogenous regressors $Z_{i1}$.)

<!-- From the rank condition  it follows that the  (Otherwise, the instrumental variables would not add any new information since they could be expressed as linear combinations of the already included exogenous variables $Z_{i1}.$) -->

[^1]: Thus if you regress each of the instruments in $Z_{i2}$ on the exogenous variables $Z_{i1}$, then the residuals of these regressions should still correlate with the endogenous variables in $Y_{i2}.$

These two requirement mean that the IVs, $Z_{i2},$

* are determined outside the systems for the endogenous variables $Y_{i1}$ and $Y_{i2}.$
* causally determine the endogenous variables $Y_{i2}.$
* not causally determine the dependent variable $Y_{i1}$ (except indirectly through their correlation with the exogenous variables $Z_{i1}$)


<!-- **Measurement error in the regressor (@exm-MeasurementError continued)** 

When $X_{i}=Z_i+u_i$ is a mis-measured version of the latent $Z_i,$ a common choice for an instrument $Z_{i2}$ is an alternative (additional) measurement 
$$
Z_{i2} =  Z_i + \tilde{u}_{i}
$$
of $Z_i.$ This additional measurement $Z_{i2}$ is an IV if

* $\tilde{u}_{i}$ is independent of $X_i.$ Since then $E(Z_{i2})$
* 

satisfy the property of an instrumental variable the measurement error in $Z_{i2}$ must be independent of that in $X_i.$ -->


## Real-Data Example: College Proximity


## References