# Instrumental Variables {#sec-IV}

## Introduction 


<!-- The method of moments estimation approach, firstly, checks whether the parameter of interest, $\beta,$ is identified; i.e., whether $\beta$ can be written in terms of population moments of observables
$$
\beta = \left(E(X_iX_i')\right)^{-1} E(X_iY_i),
$${#eq-IdentificationBeta}
where the identification result of @eq-IdentificationBeta only holds under Assumption 2 (exogeneity). The identified parameter $\beta$ is then estimated using the simple method of moments idea of substituting population moments by sample moments.  -->


We would often like to draw causal conclusions from our estimation results. In the linear regression model we saw that interpreting the slope coefficient $\beta$ causally requires many assumptions. Most importantly, the regressors have to be **exogenous** in the sense that they have to be uncorrelated 
$$
E(\varepsilon_i|X_i)=0\Rightarrow E(\varepsilon_i X_i)=Cov(\varepsilon_i,X_i)=0
$$ 
with the unobervables, $\varepsilon_i,$ in the model. 

This exogeneity assumption can be violated for many reasons. For example, we might have 

* relevant **omitted variables** or, 
* **measurement error** in the regressors $X_i.$ 

In these settings, the regressors are *endogenous* 
$$
E(\varepsilon_i|X_i) \neq 0\Rightarrow Cov(\varepsilon_i,X_i)\neq 0
$$ 
and consequently, the OLS estimator is a biased estimator of the causal effect,
$$
\begin{align*}
E(\hat{\beta}_n|X) 
&= E((X'X)^{-1}X'Y|X)\\[2ex]
&= E((X'X)^{-1}X'(X'\beta+\varepsilon)|X)\\[2ex] 
&= \beta + (X'X)^{-1}X' \; \underbrace{E(\varepsilon|X)}_{\neq 0} \neq \beta\\[2ex]
\Rightarrow &  \operatorname{Bias}(\hat{\beta}_n|X) \neq 0\\[2ex]
\Rightarrow &  E(\operatorname{Bias}(\hat{\beta}_n|X)) = \operatorname{Bias}(\hat{\beta}_n) \neq 0.
\end{align*}
$$ 

The two main solutions to the engogeneity problem are: 

* **instrumental variables** or simply instruments or IVs
* using a richer data source, namely panel data (fixed effects model), which can allow for certain unobservables to be correlated with the regressors. 

In this chapter, we focus on instrumental variables. 



For the sake of simplicity, let us focus on the simple linear regression model 
$$
Y_i = \beta_1 + \beta_2 X_{i2} + \varepsilon_i.
$$


