project:
  type: book
  output-dir: docs
  
book:
  title: Econometrics M.Sc.
  author: Prof. Dr. Dominik Liebl 
  search: true
  logo: images/Uni_Bonn_Logo.jpeg
  number-depth: 3
  chapters:
    - index.qmd
    - 01-Introduction-to-R.qmd
    - 02-Probability.qmd
    - 03-Monte-Carlo-Simulations.qmd
    - 04-Multiple-Linear-Regression.qmd
    - 05-Small-Sample-Inference.qmd
    - 06-Asymptotics.qmd
    - 07-Instrumental-Variables.qmd

bibliography: references.bib

execute:
  cache: true

format:
  html:
    theme: cosmo
