project:
  type: book
  output-dir: docs
  
book:
  title: Basis Module Econometrics (M.Sc.)
  author: Prof. Dr. Dominik Liebl 
  date: last-modified
  date-format: "[Last Updated on] MMMM DD, YYYY"
  search: true
  sidebar: 
    logo: images/Uni_Bonn_Logo.jpeg
    number-depth: 3
  chapters:
    - index.qmd
    - 01-Introduction-to-R.qmd
    - 02-Probability.qmd
    - 03-Monte-Carlo-Simulations.qmd
    - 04-Multiple-Linear-Regression.qmd
    - 05-Small-Sample-Inference.qmd
    - 06-Asymptotics.qmd
    # - 07-Instrumental-Variables.qmd

bibliography: references.bib

execute:
  cache: true

format:
  html:
    theme:
      light: [flatly, theme.scss]
      dark: [flatly, darkly, theme.scss]
    html-math-method:
      method: mathjax
      url: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML"
    monofont: Fira Mono
    mathfont: Leto
    number-sections: true
    code-link: true
    reference-links: true
    reference-location: margin
    knitr:
      opts_chunk:
        fig.align: center
        fig-align: center
