# Organization of the Course {-} 


### Timetable {-}

```{r, echo=FALSE}
suppressPackageStartupMessages(library("kableExtra"))
suppressPackageStartupMessages(library("tidyverse"))

timetable <- tibble("Day"=c("Monday", "Wednesday"),
                    "Time (UTC+2)" = c("10:15-11:45", "14:15-15:45"),
                    "Lecture Hall" = c("Jur / Hörsaal F", "	Jur / Hörsaal F"))
           
timetable %>% kbl() %>%  kable_styling()
```

### Lecture Material  

* This online script
* [eWhiteboard for lecture notes](https://www.dropbox.com/scl/fi/47ct5cqnpwbx8zsqqfbby/eWhiteboard_Metrics_2023.pdf?rlkey=yslrjdqrsgxhufbxaz10fe0z1&dl=0)
<!-- * **To-Do List for October 9, 2023:** [To-Do List (PDF)](https://www.dropbox.com/scl/fi/99tn24ky5xgsm5ghpyzhk/ToDo_List_4_Students.pdf?rlkey=mvh7z6kr0qr9drf47stcgtx9j&dl=0) -->

#### Zoom 

For students not yet in Bonn, I'll stream the lectures via [Zoom](
https://uni-bonn.zoom-x.de/j/99283287705?pwd=UHFoRTlwYkNqb0k2ODRjdEluY2FXZz09) (Meeting-ID: 992 8328 7705, Pwd: 708587) during the first lecture weeks.


### Literature {-}

The script is self-contained. To prepare well for the exam, it's a good idea to read this script. 

Further textbooks I can recommend:  

* *All of Statistics: A Concise Course in Statistical Inference*, by Larry Wasserman
* *Econometrics*, by F. Hayashi
* *Econometrics*, by Bruce E. Hansen
* *Probability and Statistics for Economists*, by Bruce E. Hansen
* *Econometric theory and methods*, by R. Davidson and J.G. MacKinnon
<!-- * *Introduction to econometrics*, by J. Stock and M.W. Watson 
  * E-Book: [https://bonnus.ulb.uni-bonn.de/SummonRecord/FETCH-bonn_catalog_45089983](https://bonnus.ulb.uni-bonn.de/SummonRecord/FETCH-bonn_catalog_45089983) -->
<!-- * *A primer in econometric theory*, by J. Stachurski -->


### Information on the Exam {-}

<!-- * Mock Exam with 5 multiple-choice problems and 1 free-text problem: [Download](https://www.dropbox.com/scl/fi/ib7z8bp2d5q775u2hoty0/Mock_Exam1.pdf?rlkey=m5yus4dkxnekpzaoydf6eqok5&dl=0) 
   * Note: The actual exam will contain 10 multiple-choice problems and 2 free-text problems. -->
* You are allowed to use a handwritten cheat-sheet (**one side** of a DIN A4 page).
* You are allowed to use a non-programmable scientific calculator.
* Please, do **not** use a pencil.
* Exam dates and times are published by the [examinations office](https://www.econ.uni-bonn.de/examinations/en/dates/dates?set_language=en)

<!-- ### Communication {-}

* You can use the Zulip-Chat [Metrics 2223 (M.Sc.)](https://ifs-bonn.zulipchat.com/join/qd5sgbusv24xsjfgbnyk5u44/) to post questions, share codes, etc. I will moderate the chat and try to answer your questions to the benefit for all. Happy sharing and discussing!  -->




