<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>6&nbsp; Small Sample Inference – Basis Module Econometrics (M.Sc.)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./07-Asymptotics.html" rel="next">
<link href="./05-Multiple-Linear-Regression.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./06-Small-Sample-Inference.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Small Sample Inference</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./images/Uni_Bonn_Logo.jpeg" alt="" class="sidebar-logo py-0 d-lg-inline d-none"></a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Basis Module Econometrics (M.Sc.)</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Organization of the Course</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Introduction-to-R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-Matrix-Algebra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Matrix Algebra</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-Monte-Carlo-Simulations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Estimation Theory and Monte Carlo Simulations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Multiple-Linear-Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Multiple Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-Small-Sample-Inference.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Small Sample Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-Asymptotics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Large Sample Inference</span></span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#sec-testmultp" id="toc-sec-testmultp" class="nav-link active" data-scroll-target="#sec-testmultp"><span class="header-section-number">6.1</span> Hypothesis Tests about Multiple Parameters (F-Tests)</a>
  <ul class="collapse">
<li><a href="#the-test-statistic-and-its-null-distribution" id="toc-the-test-statistic-and-its-null-distribution" class="nav-link" data-scroll-target="#the-test-statistic-and-its-null-distribution"><span class="header-section-number">6.1.1</span> The Test Statistic and its Null Distribution</a></li>
  </ul>
</li>
  <li><a href="#sec-testingsinglep" id="toc-sec-testingsinglep" class="nav-link" data-scroll-target="#sec-testingsinglep"><span class="header-section-number">6.2</span> Tests about One Parameter (t-Tests)</a></li>
  <li>
<a href="#testtheory" id="toc-testtheory" class="nav-link" data-scroll-target="#testtheory"><span class="header-section-number">6.3</span> Testtheory</a>
  <ul class="collapse">
<li><a href="#decisions-errors-size-and-power" id="toc-decisions-errors-size-and-power" class="nav-link" data-scroll-target="#decisions-errors-size-and-power"><span class="header-section-number">6.3.1</span> Decisions Errors, Size and Power</a></li>
  <li><a href="#significance-level-or-nominal-size" id="toc-significance-level-or-nominal-size" class="nav-link" data-scroll-target="#significance-level-or-nominal-size"><span class="header-section-number">6.3.2</span> Significance Level or Nominal Size</a></li>
  <li><a href="#rejection-regions-of-the-f-and-t-test" id="toc-rejection-regions-of-the-f-and-t-test" class="nav-link" data-scroll-target="#rejection-regions-of-the-f-and-t-test"><span class="header-section-number">6.3.3</span> Rejection Regions of the <span class="math inline">\(F\)</span> and <span class="math inline">\(t\)</span>-Test</a></li>
  <li><a href="#power-1" id="toc-power-1" class="nav-link" data-scroll-target="#power-1"><span class="header-section-number">6.3.4</span> Power</a></li>
  <li><a href="#sec-pValue" id="toc-sec-pValue" class="nav-link" data-scroll-target="#sec-pValue"><span class="header-section-number">6.3.5</span> <span class="math inline">\(p\)</span>-Value</a></li>
  </ul>
</li>
  <li><a href="#sec-CIsmallsample" id="toc-sec-CIsmallsample" class="nav-link" data-scroll-target="#sec-CIsmallsample"><span class="header-section-number">6.4</span> Confidence Intervals</a></li>
  <li>
<a href="#sec-PSSI" id="toc-sec-PSSI" class="nav-link" data-scroll-target="#sec-PSSI"><span class="header-section-number">6.5</span> Monte Carlo Simulations</a>
  <ul class="collapse">
<li><a href="#check-testing-multiple-parameters" id="toc-check-testing-multiple-parameters" class="nav-link" data-scroll-target="#check-testing-multiple-parameters"><span class="header-section-number">6.5.1</span> Check: Testing Multiple Parameters</a></li>
  <li><a href="#check-dualty-of-confidence-intervals-and-hypothesis-tests" id="toc-check-dualty-of-confidence-intervals-and-hypothesis-tests" class="nav-link" data-scroll-target="#check-dualty-of-confidence-intervals-and-hypothesis-tests"><span class="header-section-number">6.5.2</span> Check: Dualty of Confidence Intervals and Hypothesis Tests</a></li>
  </ul>
</li>
  <li><a href="#sec-RDSSInf" id="toc-sec-RDSSInf" class="nav-link" data-scroll-target="#sec-RDSSInf"><span class="header-section-number">6.6</span> Real Data Example</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">6.7</span> Exercises</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-ssinf" class="quarto-section-identifier"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Small Sample Inference</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><blockquote class="blockquote">
<p>The original version of this chapter was inspired by Chapter 1 of <span class="citation" data-cites="Hayashi2000">Hayashi (<a href="#ref-Hayashi2000" role="doc-biblioref">2000</a>)</span>. The current version, however, deviates in many aspects from <span class="citation" data-cites="Hayashi2000">Hayashi (<a href="#ref-Hayashi2000" role="doc-biblioref">2000</a>)</span>.</p>
</blockquote>
<p>In this chapter, we focus on inference with small sample sizes. It’s is very hard to say when a sample size <span class="math inline">\(n\)</span> is small. A very rough rule of thumb could be, for instance, the following one:</p>
<ul>
<li>
<span class="math inline">\(n/K&lt;20\)</span> means small samples and <span class="math inline">\(n/K\geq 20\)</span> large samples</li>
</ul>
<p>The core issue with small sample sizes is that we cannot do inference using the law of large numbers and the central limit theorem—both requiring <span class="math inline">\(n\to\infty.\)</span> Thus we need rather strict assumptions on the distribution of the error term, in order to do inference in finite samples. If these assumption are fulfilled, however, then we do <strong>exact</strong> inference.</p>
<p><strong>Exact inference:</strong> By “exact inference” we mean correct inference for each sample size <span class="math inline">\(n\)</span>. That is, no approximate results based on asymptotic <span class="math inline">\((n\to\infty)\)</span> arguments will be used.</p>
<p><strong>Assumptions:</strong> In <a href="05-Multiple-Linear-Regression.html" class="quarto-xref"><span>Chapter 5</span></a>, we did not impose a complete distributional assumption on <span class="math inline">\(\varepsilon\)</span> (see Assumption 4). For instance, the i.i.d. normal case in Assumption 4 was only one possible <em>option</em>. However, to do inference in small samples, the normality Assumption on the error terms is not a mere option, but a <em>necessity</em>.</p>
<p>Therefore, in this chapter we assume that Assumptions 1-3 from <a href="05-Multiple-Linear-Regression.html" class="quarto-xref"><span>Chapter 5</span></a> hold and that additionally the following assumption holds:</p>
<p><strong>Assumption 4<span class="math inline">\(^\boldsymbol{\ast}\)</span>: Conditional Gaussian error distribution:</strong> The error terms are Gaussian and homoskedastik, i.e., <span class="math display">\[
\varepsilon_i|X_i\sim\mathcal{N}(0,\sigma^2)
\]</span> for all <span class="math inline">\(i=1,\dots,n.\)</span></p>
<p>Assumption 4<span class="math inline">\(^\boldsymbol{\ast}\)</span> together with the random sample assumption of Assumption 1, part (b), leads to Gaussian spherical errors, <span class="math display">\[
\varepsilon|X\sim\mathcal{N}\left(0,\sigma^2I_n\right),
\]</span> where <span class="math inline">\(\varepsilon=(\varepsilon_1,\dots,\varepsilon_n)'.\)</span></p>
<!-- I.e. the distribution of $\varepsilon$ is here independent of $X.$ -->
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<div id="thm-normalbeta" class="theorem">
<p><span class="theorem-title"><strong>Theorem 6.1 (Normality of <span class="math inline">\(\hat\beta\)</span>)</strong></span> Under Assumptions 1-4<span class="math inline">\(^\ast\)</span> we have that <span id="eq-ssnorm"><span class="math display">\[
\hat\beta_n|X \sim \mathcal{N}\left(\beta,Var(\hat\beta_n|X)\right),
\qquad(6.1)\]</span></span> where <span class="math display">\[
Var(\hat\beta_n|X)=\underset{(K\times K)}{\sigma^2(X'X)^{-1}}.
\]</span></p>
</div>
</div>
</div>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>This result follows from noting that <span class="math display">\[
\begin{align*}
\hat\beta_n
&amp;=(X'X)^{-1}X'Y\\[2ex]
&amp;=\beta+(X'X)^{-1}X'\varepsilon
\end{align*}
\]</span> and because <span class="math inline">\((X'X)^{-1}X'\varepsilon\)</span> is just a linear combination of the normally distributed error terms <span class="math inline">\(\varepsilon\)</span> which, therefore, is again normally distributed, conditionally on <span class="math inline">\(X\)</span>. Note that the specific normal distribution depends on the observed realization of <span class="math inline">\(X\)</span>.</p>
</div>
<p><strong>Remark:</strong> The subscript <span class="math inline">\(n\)</span> in <span class="math inline">\(\hat\beta_n\)</span> is here only to emphasize that the distribution of <span class="math inline">\(\hat\beta_n\)</span> depends on <span class="math inline">\(n\)</span>; we will, however, often simply write <span class="math inline">\(\hat\beta\)</span>.</p>
<section id="sec-testmultp" class="level2" data-number="6.1"><h2 data-number="6.1" class="anchored" data-anchor-id="sec-testmultp">
<span class="header-section-number">6.1</span> Hypothesis Tests about Multiple Parameters (F-Tests)</h2>
<p>Let us consider the following system of <span class="math inline">\(q\)</span>-many null hypotheses: <span class="math display">\[\begin{align*}
H_0: \underset{(q\times K)}{R}\underset{(K\times 1)}{\beta}  = \underset{(q\times 1)}{r^{(0)}},
\end{align*}\]</span> where</p>
<ul>
<li>the <span class="math inline">\((q \times K)\)</span> matrix <span class="math inline">\(R,\)</span> which describes the considered linear combinations of the unknown <span class="math inline">\(\beta=(\beta_1,\dots,\beta_K)'\)</span> values, and</li>
<li>the <span class="math inline">\((q\times 1)\)</span> vector <span class="math inline">\(r^{(0)}=(r^{(0)}_{1},\dots,r^{(0)}_{q})'\)</span> of null hypothetical values</li>
</ul>
<p><strong>are chosen by the statistician</strong> to specify the null hypothesis about the unknown true parameter vector <span class="math inline">\(\beta\)</span>.</p>
<p>To make sure that there are no redundant equations, it is required that <span class="math inline">\(\operatorname{rank}(R)=q\)</span>.</p>
<p>We must also specify the alternative against which we are testing the null hypothesis, for instance <span class="math display">\[
\begin{equation*}
H_1: R\beta  \neq r^{(0)}
\end{equation*}
\]</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The above multiple parameter hypotheses cover also the special case of single parameter hypothesis; for instance, by setting</p>
<ul>
<li>
<span class="math inline">\(R=(0,1,0\dots,0)\)</span> and</li>
<li><span class="math inline">\(r^{(0)}=0\)</span></li>
</ul>
<p>we get the classic single parameter <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_1\)</span> that allows us to test the hypothesis that “<span class="math inline">\(X_{i2}\)</span> has no effect”<br><span class="math display">\[
\begin{equation*}
\begin{array}{ll}
&amp;H_0:  \beta_{2}=0 \\
\text{versus}\quad &amp;H_1:  \beta_{2} \ne 0 \\
\end{array}
\end{equation*}
\]</span> We come back to this in <a href="#sec-testingsinglep" class="quarto-xref"><span>Section 6.2</span></a>.</p>
</div>
</div>
<p>Under our assumptions (Assumptions 1 to 4<span class="math inline">\(^\ast\)</span>), we have that <span class="math display">\[
\begin{align*}
(R\hat\beta_n-r^{(0)})|X&amp;\sim\mathcal{N}\left(R\beta -r^{(0)}, RVar(\hat\beta_n|X)R'\right).
\end{align*}
\]</span></p>
<p>Thus, under the scenario that the null-hypothesis is true, we have that <span class="math display">\[
\begin{align*}
(R\hat\beta_n-r^{(0)})|X&amp;\overset{{\color{red}{H_0}}}{\sim}\mathcal{N}\left(\phantom{RV}{\color{red}0}\phantom{RR},RVar(\hat\beta_n|X)R'\right).
\end{align*}
\]</span></p>
<p>That is:</p>
<ul>
<li>The realizations of <span class="math display">\[
(R\hat\beta_n -r^{(0)})|X
\]</span> will scatter around the <em>unknown</em> mean <span class="math inline">\((R\beta -r^{(0)})\)</span> in a Gaussian fashion.</li>
<li>If <span class="math inline">\(H_0\)</span> is correct (i.e., if <span class="math inline">\(R\beta-r^{(0)}=0\)</span>), the realizations of <span class="math display">\[
(R\hat\beta_n-r^{(0)})|X
\]</span> will scatter around the <span class="math inline">\((q\times 1)\)</span> vector <span class="math inline">\(0.\)</span>
</li>
</ul>
<p>We use a test statistic to detect a systematic location shift away from the <span class="math inline">\((q\times 1)\)</span> vector <span class="math inline">\(0.\)</span></p>
<!-- * if the alternative hypothesis is correct (i.e., $(R\beta-r)=a\neq 0$), there will be a systematic location-shift in $(R\hat\beta_n-r)|X$ which we try to detect using statistical hypothesis testing.  -->
<!-- the realizations of $R\hat\beta_n-r|X$ scatter around the $q$-vector $a\neq 0$.  So, under the alternative hypothesis,  -->
<section id="the-test-statistic-and-its-null-distribution" class="level3" data-number="6.1.1"><h3 data-number="6.1.1" class="anchored" data-anchor-id="the-test-statistic-and-its-null-distribution">
<span class="header-section-number">6.1.1</span> The Test Statistic and its Null Distribution</h3>
<p>The fact that <span class="math display">\[
(R\hat\beta_n-r^{(0)})\in\mathbb{R}^q
\]</span> is a <span class="math inline">\(q\)</span>-dimensional random variable makes it a little bothersome to use as a test-statistic. Fortunately, we can turn <span class="math inline">\((R\hat\beta_n-r^{(0)})\)</span> into a scalar-valued test statistic using the following quadratic form: <span class="math display">\[
W=\underbrace{(R\hat\beta_n -r^{(0)})'}_{(1\times q)}\underbrace{[RVar(\hat\beta_n|X)R']^{-1}}_{(q\times q)}\underbrace{(R\hat\beta_n -r^{(0)})}_{(q\times 1)}
\]</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Note that the test statistic <span class="math inline">\(W\)</span> is simply measuring the distance (it’s a weighted Euclidean distance) between the <span class="math inline">\((q\times 1)\)</span> vectors <span class="math inline">\(R\hat\beta_n\)</span> and <span class="math inline">\(r^{(0)}.\)</span></p>
</div>
</div>
<p>Under the null hypothesis (i.e., if <span class="math inline">\(H_0\)</span> is true), <span class="math inline">\(W|X\)</span> is a sum of <span class="math inline">\(q\)</span>-many independent squared standard normal random variables. Therefore, under the null hypothesis, <span class="math inline">\(W|X\)</span> is chi-square distributed with <span class="math inline">\(q\)</span> degrees of freedom (see <a href="02-Probability.html#sec-chisqdist" class="quarto-xref"><span>Section 2.2.10.3</span></a>), <span class="math display">\[
\begin{align*}
W|X&amp;\overset{H_0}{\sim} \chi^2_{(q)}\\
\Rightarrow \quad\quad W&amp;\overset{H_0}{\sim} \chi^2_{(q)}
\end{align*}
\]</span> Note that the distribution of <span class="math inline">\(W|X\)</span> does not depend on <span class="math inline">\(X.\)</span> I.e. <span class="math inline">\(W|X\)</span> follows a <span class="math inline">\(\chi^2_{(q)}\)</span>-distribution no matter the realization of <span class="math inline">\(X.\)</span> Thus our test decisions do not depend on the values of <span class="math inline">\(X.\)</span> (Good news!)</p>
<p>Usually, we do not know <span class="math inline">\(Var(\hat\beta_n|X),\)</span> and thus we need to estimate this quantity from the data. Unfortunately, in the small sample case, we can only deal with homoskedastic error terms. For truly exact finite sample inference, we need a variance estimator for which we can derive the exact small sample distribution. Therefore, we require Assumption 4<span class="math inline">\(^*\)</span> of spherical errors (i.e., <span class="math inline">\(Var(\varepsilon|X)=I_n\sigma^2\)</span>) which yields that <span class="math inline">\(Var(\hat\beta_n|X)=\sigma^2(X'X)^{-1}\)</span>, and where <span class="math inline">\(\sigma^2\)</span> can be estimated by the unbiased (<span class="math inline">\(UB\)</span>) variance estimator<br><span class="math display">\[
s_{UB}^2=(n-K)^{-1}\sum_{i=1}^n\hat\varepsilon_i^2.
\]</span><br>
From the normality assumption in Assumption 4<span class="math inline">\(^*\)</span>, it follows then that <span id="eq-distsquared"><span class="math display">\[
\frac{(n-K)}{\sigma^{2}}s_{UB}^2\sim\chi^2_{(n-K)}.
\qquad(6.2)\]</span></span></p>
<p>The <span class="math inline">\(F\)</span> test statistic uses then <span class="math inline">\(s_{UB}^2\)</span> as an estimator of <span class="math inline">\(\sigma^2\)</span> <span class="math display">\[
F=(R\hat\beta_n -r^{(0)})'[R(s_{UB}^2(X'X)^{-1})R']^{-1}(R\hat\beta_n -r^{(0)})/q
\]</span> and takes into account the additional randomness (estimation errors) due to <span class="math inline">\(s_{UB}^2\)</span>, which leads to the following exact null distribution of the <span class="math inline">\(F\)</span> test <span id="eq-Ftest"><span class="math display">\[
F\overset{H_0}{\sim} F_{(q,n-K)},
\qquad(6.3)\]</span></span> where <span class="math inline">\(F_{(q,n-K)}\)</span> denotes the <span class="math inline">\(F\)</span>-distribution with <span class="math inline">\(q\)</span> numerator and <span class="math inline">\(n-K\)</span> denominator degrees of freedom.</p>
<p>As in the case of <span class="math inline">\(W\)</span>, the distribution of <span class="math inline">\(F\)</span> conditional on <span class="math inline">\(X\)</span> does not depend on <span class="math inline">\(X\)</span>; i.e.&nbsp;<span class="math inline">\(F|X\overset{H_0}{\sim}F_{(q,n-K)},\)</span> but <span class="math inline">\(F_{(q,n-K)}\)</span> does not depend on <span class="math inline">\(X,\)</span> thus we can write <span class="math inline">\(F\overset{H_0}{\sim}F_{(q,n-K)}.\)</span></p>
<blockquote class="blockquote">
<p>The distributional statements in <a href="#eq-distsquared" class="quarto-xref">Equation&nbsp;<span>6.2</span></a> and <a href="#eq-Ftest" class="quarto-xref">Equation&nbsp;<span>6.3</span></a> are a little cumbersome to derive and we do not go into details here, but in case you’re interested you can find some more details, for instance, in Chapter 1 of <span class="citation" data-cites="Hayashi2000">Hayashi (<a href="#ref-Hayashi2000" role="doc-biblioref">2000</a>)</span>.</p>
</blockquote>
<p>By contrast to <span class="math inline">\(W,\)</span> <span class="math inline">\(F\)</span> is now a practically useful test statistic, and we can use the observed value <span class="math inline">\(F_{\text{obs}}\)</span> to measure the distance of our observed estimate <span class="math inline">\(R\hat\beta_n\)</span> from its null-hypothetical value <span class="math inline">\(r^{(0)}.\)</span></p>
<p>Observed values, <span class="math inline">\(F_{\text{obs}}\)</span>, that are “unusually large” under the null hypothesis, lead to a rejection of the null hypothesis. The null distribution <span class="math inline">\(F_{(q,n-K)}\)</span> of <span class="math inline">\(F\)</span> is used to judge what’s “unusually large” under the null hypothesis.</p>
<p><strong>The F distribution.</strong> The F distribution is a ratio of two <span class="math inline">\(\chi^2\)</span> distributions. It has two parameters: the numerator degrees of freedom, and the denominator degrees of freedom. Each combination of the parameters yields a different F distribution. See <a href="02-Probability.html#sec-Fdist" class="quarto-xref"><span>Section 2.2.10.6</span></a> for more information on the <span class="math inline">\(F\)</span> distribution.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="06-Small-Sample-Inference_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</section></section><section id="sec-testingsinglep" class="level2" data-number="6.2"><h2 data-number="6.2" class="anchored" data-anchor-id="sec-testingsinglep">
<span class="header-section-number">6.2</span> Tests about One Parameter (t-Tests)</h2>
<p>A hypothesis about only <strong>one parameter</strong> <span class="math display">\[
\begin{equation*}
\begin{array}{ll}
&amp; H_0: \beta_k=\beta_k^{(0)}\\
\text{versus}\quad &amp; H_1: \beta_k\ne \beta_k^{(0)}\\
\end{array}
\end{equation*}
\]</span> is simply a special case of the general null hypothesis <span class="math inline">\(H_0:R\beta =r^{(0)},\)</span> where</p>
<ul>
<li>
<span class="math inline">\(R\)</span> is a <span class="math inline">\((1\times K)\)</span> row-vector of zeros, but with a one as the <span class="math inline">\(k\)</span>th element, and where</li>
<li>we write <span class="math inline">\(r^{(0)}=\beta_k^{(0)}\)</span> since we make a hypothesis only about <span class="math inline">\(\beta_k.\)</span>
</li>
</ul>
<p>Thus the <span class="math inline">\(F\)</span>-test statistic simplifies to <span class="math display">\[
F=\frac{\left(\hat{\beta}_k-\beta_k^{(0)}\right)^2}{\widehat{Var}(\hat{\beta}_k|X)}\overset{H_0}{\sim}F_{(1,n-K)},
\]</span> where <span class="math display">\[
\widehat{Var}(\hat{\beta}_k|X)=s^2_{UB}[(X'X)^{-1}]_{(k,k)},
\]</span> and where <span class="math inline">\([(X'X)^{-1}]_{(k,k)}\)</span> denotes the element in the <span class="math inline">\(k\)</span>th row and <span class="math inline">\(k\)</span>th column of the <span class="math inline">\((K\times K)\)</span> matrix <span class="math inline">\((X'X)^{-1}.\)</span></p>
<p>Taking square roots yields the <span class="math inline">\(t\)</span> test statistic <span class="math display">\[
T=\frac{\hat{\beta}_k-\beta_k^{(0)}}{\widehat{\operatorname{SE}}(\hat{\beta}_k|X)}\overset{H_0}{\sim}t_{(n-K)},
\]</span> where <span class="math display">\[
\widehat{\operatorname{SE}}(\hat{\beta}_k|X)
=\sqrt{\widehat{Var}(\hat{\beta}_k|X)}=s_{UB}[(X'X)^{-1/2}]_{(k,k)},
\]</span> and where <span class="math inline">\(t_{(n-K)}\)</span> denotes the <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n-K\)</span> degrees of freedom.</p>
<p>Thus the <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n-K\)</span> degrees of freedom is the appropriate distribution to judge whether or not an observed value <span class="math inline">\(T_{\text{obs}}\)</span> of the test statistic is “unusually large” under the null hypothesis.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>All commonly used statistical software packages report <span class="math inline">\(t\)</span>-tests testing the null hypothesis <span class="math display">\[
H_0:\beta_k=0
\]</span> for each <span class="math inline">\(k=1,\dots,K.\)</span> This means to test the null hypothesis that <span class="math inline">\(X_k\)</span> has “no (linear) effect” on the conditional mean of <span class="math inline">\(Y\)</span> given <span class="math inline">\(X.\)</span></p>
</div>
</div>
<p><strong>The <span class="math inline">\(t\)</span> distribution.</strong> The following plot illustrates that as the degrees of freedom increase, the shape of the <span class="math inline">\(t\)</span> distribution comes closer to that of a standard normal bell curve. Already for <span class="math inline">\(25\)</span> degrees of freedom we find little difference to the standard normal density. In case of small degrees of freedom values, we find the distribution to have heavier tails than a standard normal. See <a href="02-Probability.html#sec-tdist" class="quarto-xref"><span>Section 2.2.10.4</span></a> for more information about the <span class="math inline">\(t\)</span>-distribution.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="06-Small-Sample-Inference_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</section><section id="testtheory" class="level2" data-number="6.3"><h2 data-number="6.3" class="anchored" data-anchor-id="testtheory">
<span class="header-section-number">6.3</span> Testtheory</h2>
<p>Every statistical test statistic is a function of the random sample, i.e. <span class="math display">\[
T\equiv T((X_1,Y_1),\dots,(X_n,Y_n))
\]</span> and is thus a random variable.</p>
<p><strong>Caution:</strong> In this section, <span class="math inline">\(T\)</span> denotes <em>any</em> test statistic. Specific examples for <span class="math inline">\(T\)</span> are, for instance,</p>
<ul>
<li>the <span class="math inline">\(F\)</span>-test statistic (<a href="#sec-testmultp" class="quarto-xref"><span>Section 6.1</span></a>) and</li>
<li>the <span class="math inline">\(t\)</span>-test statistic (<a href="#sec-testingsinglep" class="quarto-xref"><span>Section 6.2</span></a>).</li>
</ul>
<p>Generally, we can only derive the distribution of <span class="math inline">\(T\)</span> under <span class="math inline">\(H_0;\)</span> i.e.&nbsp;under the scenario that <span class="math inline">\(H_0\)</span> is true, <span class="math display">\[
\begin{equation*}
\begin{array}{ll}
T &amp; \overset{{H_0}}\sim f_T\quad ✅
\end{array}
\end{equation*}
\]</span> For instance, in case of the <span class="math inline">\(F\)</span>-test, <span class="math inline">\(f_T\)</span> is the <span class="math inline">\(F\)</span>-distribution and in case of the <span class="math inline">\(t\)</span>-test, <span class="math inline">\(f_T\)</span> is the <span class="math inline">\(t\)</span>-distribution.</p>
<p>However, the distribution of <span class="math inline">\(T\)</span> under <span class="math inline">\(H_1\)</span> is typically unknown. <span class="math display">\[
\begin{equation*}
\begin{array}{ll}
T &amp; \overset{{H_1}}\sim ❓
\end{array}
\end{equation*}
\]</span></p>
<!-- * in @sec-testmultp we discussed that $F\overset{H_0}{\sim} F_{(q,n-K)}.$

* in @sec-testingsinglep we discussed (for simple null hypothesis) that $T\overset{H_0}{\sim} t_{(n-K)}$ -->
<p>We use the observed realization <span class="math display">\[
T_{\text{obs}}\equiv T((X_{1,\text{obs}},Y_{1,\text{obs}}),\dots,(X_{n,\text{obs}},Y_{n,\text{obs}}))
\]</span> of the random test statistic <span class="math inline">\(T\)</span> to decide:</p>
<ul>
<li>whether we cannot reject a null hypothesis <span class="math inline">\(H_0\)</span> about some parameter <span class="math inline">\(\theta\)</span> <span class="math display">\[
H_0: \theta\in\Theta_0
\]</span>
</li>
<li>or wether we can reject <span class="math inline">\(H_0\)</span> in favor of the alternative hypothesis <span class="math inline">\(H_1\)</span> <span class="math display">\[
H_1: \theta\in\Theta_1
\]</span>
</li>
</ul>
<p>Notation:</p>
<ul>
<li>
<span class="math inline">\(\Theta_0\)</span> denotes the set of parameter values <span class="math inline">\(\theta\)</span> under <span class="math inline">\(H_0\)</span>.</li>
<li>
<span class="math inline">\(\Theta_1\)</span> denotes the set of parameter values <span class="math inline">\(\theta\)</span> under <span class="math inline">\(H_1\)</span>.</li>
</ul>
<p>It is required that <span class="math display">\[
\Theta_0 \cap \Theta_1 = \emptyset.
\]</span></p>
<p><strong>Simple</strong> versus <strong>composite</strong> hypotheses:</p>
<ul>
<li>If <span class="math inline">\(\Theta_j,\)</span> <span class="math inline">\(j=1,2,\)</span> contains only <strong>one value</strong> <span class="math display">\[
\Theta_j=\theta^{(j)},
\]</span> it is called a <strong>simple hypothesis</strong>.</li>
<li>If <span class="math inline">\(\Theta_j,\)</span> <span class="math inline">\(j=1,2,\)</span> contains <strong>multiple values</strong>, it is called a <strong>composite hypothesis</strong>.</li>
</ul>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example: Two-Sided Test with <span class="math inline">\(\theta\in\mathbb{R}\)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[
\begin{equation*}
\begin{array}{ll}
&amp; H_0: \theta = \theta^{(0)}\\
\text{versus}\quad
&amp; H_1: \theta\neq \theta^{(0)}\\
\end{array}
\end{equation*}
\]</span></p>
<p>Here we have a <strong>simple</strong> null hypothesis <span class="math display">\[
\Theta_0=\theta^{(0)}
\]</span> and a <strong>composite</strong> alternative hypothesis <span class="math display">\[
\Theta_1=\mathbb{R}\setminus\theta^{(0)}.
\]</span></p>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example: One-Sided Test with <span class="math inline">\(\theta\in\mathbb{R}\)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[
\begin{equation*}
\begin{array}{ll}
&amp; H_0: \theta \geq  \theta^{(0)}\\
\text{versus}\quad
&amp; H_1: \theta  &lt; \theta^{(0)}\\
\end{array}
\end{equation*}
\]</span></p>
<p>Here we have a <strong>composite</strong> null hypothesis <span class="math display">\[
\Theta_0=\;[\theta^{(0)},\infty[
\]</span> and a <strong>composite</strong> alternative hypothesis <span class="math display">\[
\Theta_1=\;]-\infty,\theta^{(0)}[.
\]</span></p>
<p>Likewise for the other direction of the one-sided test.</p>
</div>
</div>
<section id="decisions-errors-size-and-power" class="level3" data-number="6.3.1"><h3 data-number="6.3.1" class="anchored" data-anchor-id="decisions-errors-size-and-power">
<span class="header-section-number">6.3.1</span> Decisions Errors, Size and Power</h3>
<p>Hypothesis testing is like a legal trial. We assume someone is innocent unless the evidence strongly suggests that he is guilty. Similarly, we retain <span class="math inline">\(H_0\)</span> unless there is strong evidence to reject <span class="math inline">\(H_0.\)</span></p>
<ul>
<li><p>We <strong>reject</strong> <span class="math inline">\(H_0\)</span> if <span class="math display">\[
T_{\text{obs}}\in \mathcal{R},
\]</span> where <span class="math inline">\(\mathcal{R}\)</span> denotes the <strong>rejection region</strong>; i.e.&nbsp;a range of <span class="math inline">\(T\)</span> values that we see only very rarely under <span class="math inline">\(H_0.\)</span> <!-- </br>(Extreme: in direction of $H_1;$ i.e. very large or very small in comparision to the null distribution of $T.$)  --></p></li>
<li><p>We <strong>cannot reject</strong> <span class="math inline">\(H_0\)</span> <span class="math display">\[
T_{\text{obs}}\not \in \mathcal{R}
\]</span></p></li>
</ul>
<p>We differentiate two decision errors:</p>
<ul>
<li>
<strong>type-I-error:</strong> If we reject <span class="math inline">\(H_0\)</span> even though <span class="math inline">\(H_0\)</span> is true.</li>
<li>
<strong>type-II-error:</strong> If we do not reject <span class="math inline">\(H_0\)</span> even though <span class="math inline">\(H_1\)</span> is true.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Size
</div>
</div>
<div class="callout-body-container callout-body">
<p>The probability of a type-I-error event is also called <strong>size</strong> of <span class="math inline">\(T.\)</span></p>
<p>The size of <span class="math inline">\(T\)</span> is defined as the larges probability of rejecting <span class="math inline">\(H_0\)</span> over all possible parameter values <span class="math inline">\(\theta\in\Theta_0\)</span> under <span class="math inline">\(H_0,\)</span> <span class="math display">\[\begin{align*}
\text{Size}
=&amp; \sup_{\theta\in\Theta_0} P(T \in \mathcal{R}).
\end{align*}\]</span></p>
<p>Since we want to be sure that we correctly reject <span class="math inline">\(H_0,\)</span> we want test statistics for which we can control the their size from above by some chosen level; e.g.&nbsp;</p>
<ul>
<li>
<span class="math inline">\(\text{Size}\,\leq 0.05\)</span> or</li>
<li><span class="math inline">\(\text{Size}\,\leq 0.01.\)</span></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Power
</div>
</div>
<div class="callout-body-container callout-body">
<p>One minus the probability of a type-II-error is called <strong>power</strong> of <span class="math inline">\(T.\)</span></p>
<p>The power of <span class="math inline">\(T\)</span> is defined as <span class="math display">\[\begin{align*}
\text{Power}=&amp;1-P(\text{type-II-error})\\[2ex]
=&amp;P(T\in \mathcal{R} | \theta\in \Theta_1)
\end{align*}\]</span> Since we want to detect violations of <span class="math inline">\(H_0,\)</span> we want test statistics with a large power.</p>
</div>
</div>
</section><section id="significance-level-or-nominal-size" class="level3" data-number="6.3.2"><h3 data-number="6.3.2" class="anchored" data-anchor-id="significance-level-or-nominal-size">
<span class="header-section-number">6.3.2</span> Significance Level or Nominal Size</h3>
<p>Let <span class="math inline">\(\alpha\)</span> with <span class="math inline">\(0&lt;\alpha&lt;1\)</span> denote the <strong>significance level</strong> chosen by the statistician/econometrician.</p>
<p>A statistical hypothesis test, <span class="math inline">\(T,\)</span> is a <strong>valid test</strong> if its size (probability of a type-I-error) can be bounded from above by the chosen <strong>significance level (nominal size)</strong> <span class="math inline">\(\alpha\)</span>, i.e.&nbsp;if<br><span class="math display">\[\begin{align*}
\text{Size}=P(\text{reject } H_0| H_0\text{ is true})\; \leq\; \alpha = \text{Nominal Size}
\end{align*}\]</span></p>
<p>Since we want to keep the probability of falsely rejecting <span class="math inline">\(H_0\)</span> small, we choose small singificance levels such as</p>
<ul>
<li>
<span class="math inline">\(\alpha=0.05\)</span> or</li>
<li>
<span class="math inline">\(\alpha=0.01\)</span> or</li>
<li><span class="math inline">\(\alpha=0.001,\)</span></li>
</ul>
<p>but of course, these values are only conventions and you can also choose, for instance, <span class="math inline">\(\alpha=0.026.\)</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exact vs conservative vs invalid
</div>
</div>
<div class="callout-body-container callout-body">
<p>A test statistic <span class="math inline">\(T\)</span> is called <strong>exact (or non-conservative)</strong> if <span class="math display">\[
\text{Size}=\sup_{\theta\in\Theta_0} P(T \in \mathcal{R}) =\alpha.
\]</span> A test statistic <span class="math inline">\(T\)</span> is called <strong>conservative</strong> if <span class="math display">\[
\text{Size}= \sup_{\theta\in\Theta_0} P(T \in \mathcal{R}) &lt;\alpha.
\]</span> A test statistic <span class="math inline">\(T\)</span> is called <strong>invalid</strong> if <span class="math display">\[
\text{Size}=\sup_{\theta\in\Theta_0} P(T \in \mathcal{R}) &gt; \alpha.
\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Under Assumptions 1-4<span class="math inline">\(^\ast,\)</span> the <span class="math inline">\(F\)</span>-test and the <span class="math inline">\(t\)</span>-test are <strong>exact</strong> test statistics.</p>
</div>
</div>
</div>
</div>
<!-- and a given alternative hypothesis, we can divide the range of all possible values of the test statistic (i.e., $\mathbb{R}$ since both $t\in\mathbb{R}$ and $F\in\mathbb{R}$) into a **rejection region** and a **non-rejection region** by using **critical values** derived from the distribution of the test statistic under the null hypothesis.  We can do this because the test statistics $t$ and $F$ have known distributions under the null hypothesis ($t\overset{H_0}{\sim}t_{n-K}$ and $F\overset{H_0}{\sim}F_{(q,n-K)}$).  -->
</section><section id="rejection-regions-of-the-f-and-t-test" class="level3" data-number="6.3.3"><h3 data-number="6.3.3" class="anchored" data-anchor-id="rejection-regions-of-the-f-and-t-test">
<span class="header-section-number">6.3.3</span> Rejection Regions of the <span class="math inline">\(F\)</span> and <span class="math inline">\(t\)</span>-Test</h3>
<p>To decide whether we can reject <span class="math inline">\(H_0\)</span>, we need to compare the observed value <span class="math inline">\(T_{\text{obs}}\)</span> with the distribution of <span class="math inline">\(T\)</span> under <span class="math inline">\(H_0.\)</span> This can be done using</p>
<ul>
<li><strong>rejection regions/critical values,</strong></li>
<li>
<strong><span class="math inline">\(p\)</span>-values</strong> (<a href="#sec-pValue" class="quarto-xref"><span>Section 6.3.5</span></a>) or<br>
</li>
<li>
<strong>confidence intervals</strong> (<a href="#sec-CIsmallsample" class="quarto-xref"><span>Section 6.4</span></a>)</li>
</ul>
<p>All of these options lead to equivalent test decisions.</p>
<p>The <strong>rejection region</strong> for a statistical test statistic <span class="math inline">\(T\)</span> is defined using <strong>critical values</strong> which are certain quantiles of the distribution of <span class="math inline">\(T\)</span> under <span class="math inline">\(H_0.\)</span></p>
<section id="rejection-regions-of-the-f-test" class="level4" data-number="6.3.3.1"><h4 data-number="6.3.3.1" class="anchored" data-anchor-id="rejection-regions-of-the-f-test">
<span class="header-section-number">6.3.3.1</span> Rejection Regions of the <span class="math inline">\(F\)</span>-Test</h4>
<p>The <span class="math inline">\(F\)</span>-test allows us to test <span class="math display">\[
\begin{align*}
&amp;H_0: R\beta = r^{(0)}\\[2ex]
\text{versus}\quad
&amp;H_1: R\beta\neq r^{(0)},
\end{align*}
\]</span> where <span class="math inline">\(\beta\)</span> denotes the true (unknown) parameter vector and <span class="math inline">\(r^{(0)}\)</span> the null-hypothetical value specified by the statistician (often, e.g.&nbsp;<span class="math inline">\(r^{(0)}\)</span>).</p>
<p>Under Assumptions 1-4<span class="math inline">\(^\ast\)</span> (see <a href="#sec-testmultp" class="quarto-xref"><span>Section 6.1</span></a>), we have that <span id="eq-FNullDistr"><span class="math display">\[
F\overset{H_0}{\sim}F_{q,n-K}.
\qquad(6.4)\]</span></span></p>
<p>Let <span class="math inline">\(0&lt;\alpha&lt;1\)</span> denote the significance level and let <span class="math inline">\(c_{1-\alpha}\)</span> denote the <span class="math inline">\((1-\alpha)\)</span> quantile of the <span class="math inline">\(F\)</span>-distribution with <span class="math inline">\((q,n-K)\)</span> degrees of freedom.</p>
<p>This quantile <span class="math inline">\(c_{1-\alpha}\)</span> is the <strong>critical value</strong> that defines the <strong>rejection region</strong>: <span class="math display">\[
\mathcal{R}=\; ]c_{1-\alpha},\infty[
\]</span> <!-- , and 
- non-rejection region, $]0,c_{1-\alpha}]$  --></p>
<ul>
<li>We can rejection <span class="math inline">\(H_0\)</span> if <span class="math display">\[
F_{obs}\in \mathcal{R}=\; ]c_{1-\alpha},\infty[
\]</span>
</li>
<li>We cannot rejection <span class="math inline">\(H_0\)</span> if <span class="math display">\[
F_{obs}\not \in \mathcal{R}=\; ]c_{1-\alpha},\infty[
\]</span>
</li>
</ul>
<p><a href="#eq-FNullDistr" class="quarto-xref">Equation&nbsp;<span>6.4</span></a> allows us to show that the <span class="math inline">\(F\)</span>-test is an exact test. Since the null hypothesis is a <strong>simple</strong> hypothesis, we have that <span class="math display">\[\begin{align*}
\text{Size}
=&amp;\sup_{\theta\in\Theta_0}P(T \in \mathcal{R})\\[2ex]
=&amp;P(F \in \mathcal{R} \;|\; R\beta = r^{(0)}).
\end{align*}\]</span> Thus, <span class="math display">\[\begin{align*}
\text{Size}
=&amp;P(F\in\mathcal{R}\;|\;R\beta = r^{(0)})\\[2ex]
=&amp;P\Big(F &gt; c_{1-\alpha}\;|\;R\beta = r^{(0)}\Big)\\[2ex]
=&amp;1 - P\Big(F \leq c_{1-\alpha}\;|\;R\beta = r^{(0)}\Big)=\alpha,
\end{align*}\]</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="06-Small-Sample-Inference_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>The rejection region:</strong> The rejection region describes a range of values of the test statistic <span class="math inline">\(F\)</span> which we rarely see if the null hypothesis is true (only in at most <span class="math inline">\(\alpha \cdot 100\%\)</span> cases). If the observed value of the test statistic, <span class="math inline">\(F_{\text{obs}}\)</span>, falls in this region, we will reject the null hypothesis and acknowledge a type-I-error rate of at most <span class="math inline">\(\alpha\)</span>.</p>
<p><strong>The non-rejection region:</strong> The non-rejection region describes a range of values of the test statistic <span class="math inline">\(F\)</span> which we expect to see (in <span class="math inline">\((1-\alpha) \cdot 100\%\)</span> cases) if the null hypothesis is true. If the observed value of the test statistic, <span class="math inline">\(F_{\text{obs}}\)</span> falls in this region, we cannot reject the null hypothesis.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Caution
</div>
</div>
<div class="callout-body-container callout-body">
<p>If we cannot reject <span class="math inline">\(H_0,\)</span> does not mean that we confirm <span class="math inline">\(H_0.\)</span></p>
<p>A possible violation of the null hypothesis may only be too small to stand out from the estimation errors; i.e.&nbsp;we may do a type-II-error. However, we do not control the probability of type-II-errors—we only control the probability of type-I-errors.</p>
<p>Therefore, if you were not able to reject <span class="math inline">\(H_0,\)</span> <strong>never ever</strong> state something like: “I conclude <span class="math inline">\(H_0\)</span> is true.”</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
For the special case of a “no-effect” null hypothesis <span class="math display">\[
H_0:\beta_k=0,
\]</span> there’s a famous sentence which goes back to <span class="citation" data-cites="Altman_Bland_1995">Altman and Bland (<a href="#ref-Altman_Bland_1995" role="doc-biblioref">1995</a>)</span> :
<center>
“Absence of evidence is not evidence of absence.”
</center>
</div>
</div>
</div>
</div>
<p>To find the critical value <span class="math inline">\(c_{1-\alpha}\)</span> we can use <code>R</code> as following:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">alpha</span> <span class="op">&lt;-</span> <span class="fl">0.05</span> <span class="co"># chosen significance level</span></span>
<span><span class="va">df1</span>   <span class="op">&lt;-</span> <span class="fl">9</span>    <span class="co"># numerator df</span></span>
<span><span class="va">df2</span>   <span class="op">&lt;-</span> <span class="fl">120</span>  <span class="co"># denominator df</span></span>
<span></span>
<span><span class="co">## Critical value:</span></span>
<span><span class="va">crit_value</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Fdist.html">qf</a></span><span class="op">(</span>p <span class="op">=</span> <span class="fl">1</span><span class="op">-</span><span class="va">alpha</span>, df1 <span class="op">=</span> <span class="va">df1</span>, df2 <span class="op">=</span> <span class="va">df2</span><span class="op">)</span></span>
<span><span class="va">crit_value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.958763</code></pre>
</div>
</div>
<p>Changing the significance level from <span class="math inline">\(\alpha=0.05\)</span> to <span class="math inline">\(\alpha=0.01\)</span> makes the critical value <span class="math inline">\(c_{1-\alpha}\)</span> larger and, therefore, the rejection region smaller (smaller probability of type-I-errors).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">alpha</span> <span class="op">&lt;-</span> <span class="fl">0.01</span> <span class="co"># chosen significance level</span></span>
<span><span class="co">## Critical value:</span></span>
<span><span class="va">crit_value</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Fdist.html">qf</a></span><span class="op">(</span>p <span class="op">=</span> <span class="fl">1</span><span class="op">-</span><span class="va">alpha</span>, df1 <span class="op">=</span> <span class="va">df1</span>, df2 <span class="op">=</span> <span class="va">df2</span><span class="op">)</span></span>
<span><span class="va">crit_value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.558574</code></pre>
</div>
</div>
</section><section id="rejection-regions-of-the-two-sided-t-test" class="level4" data-number="6.3.3.2"><h4 data-number="6.3.3.2" class="anchored" data-anchor-id="rejection-regions-of-the-two-sided-t-test">
<span class="header-section-number">6.3.3.2</span> Rejection Regions of the Two-Sided <span class="math inline">\(t\)</span>-Test</h4>
<p>The two-sided <span class="math inline">\(t\)</span>-test allows us to test <span class="math display">\[\begin{align*}
&amp; H_0: \beta_k=\beta_k^{(0)}\\
\text{versus}\quad
&amp; H_1: \beta_k\ne \beta_k^{(0)}
\end{align*}\]</span> where <span class="math inline">\(\beta_k\)</span> denotes the true (unknown) parameter value and <span class="math inline">\(\beta_k^{(0)}\)</span> the null hypothetical value specified by the statistician (e.g.&nbsp;<span class="math inline">\(\beta_k^{(0)}=0\)</span>).</p>
<p>Under Assumptions 1-4<span class="math inline">\(^\ast\)</span> (see <a href="#sec-testingsinglep" class="quarto-xref"><span>Section 6.2</span></a>), we have that <span id="eq-T2SNullDistr"><span class="math display">\[
T\overset{H_0}{\sim}t_{n-K}.
\qquad(6.5)\]</span></span></p>
<p>Let <span class="math inline">\(0&lt;\alpha&lt;1\)</span> denote the significance level and let <span class="math inline">\(c_{\alpha/2}\)</span> and <span class="math inline">\(c_{1-\alpha/2}\)</span> denote the <span class="math inline">\(\alpha/2\)</span> and the <span class="math inline">\((1-\alpha/2)\)</span> quantiles of the <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\((n-K)\)</span> degrees of freedom.</p>
<p>These quantiles are the <strong>critical values</strong> that define the <strong>rejection region</strong> of the two-sided <span class="math inline">\(t\)</span>-test: <span class="math display">\[
\mathcal{R}=\;]-\infty,c_{\alpha/2}[\;\;\cup\;\;]c_{1-\alpha/2}, \infty[
\]</span></p>
<ul>
<li>We can reject <span class="math inline">\(H_0\)</span> if <span class="math display">\[\begin{align*}
T_{obs}
&amp; \in \mathcal{R}%\\[2ex]
%&amp; \in \;]-\infty,c_{\alpha/2}[\;\;\cup\;\;]c_{1-\alpha/2}, \infty[
\end{align*}\]</span>
</li>
<li>We cannot reject <span class="math inline">\(H_0\)</span> if <span class="math display">\[\begin{align*}
T_{obs}
&amp;\not \in \mathcal{R}%\\[2ex]
%&amp;\not \in \;]-\infty,c_{\alpha/2}[\;\;\cup\;\;]c_{1-\alpha/2}, \infty[
\end{align*}\]</span>
</li>
</ul>
<p><a href="#eq-T2SNullDistr" class="quarto-xref">Equation&nbsp;<span>6.5</span></a> allows us to show that the <span class="math inline">\(t\)</span>-test is an exact test. Since the two-sided null hypothesis is a <strong>simple hypothesis</strong>, we have that <span class="math display">\[\begin{align*}
\text{Size}
=&amp;\sup_{\theta\in\Theta_0}P(T \in \mathcal{R})\\[2ex]
=&amp;P(T \in \mathcal{R} \;|\; \beta_k = \beta_k^{(0)}).
\end{align*}\]</span> Thus, <span class="math display">\[\begin{align*}
\text{Size}
=&amp;P(T \in \mathcal{R} \;|\; \beta_k = \beta_k^{(0)})\\[2ex]
=&amp;P\Big(T &lt; c_{\alpha/2}\quad\text{or}\quad T&gt;c_{1-\alpha/2} \;\Big|\; \beta_k = \beta_k^{(0)}\Big)\\[2ex]
=&amp;P\Big(T &lt; c_{\alpha/2} \;\Big|\; \beta_k = \beta_k^{(0)}\Big) +
  P\Big(T&gt;c_{1-\alpha/2} \;\Big|\; \beta_k = \beta_k^{(0)}\Big)\\[2ex]
&amp;=\frac{\alpha}{2}+\frac{\alpha}{2}=\alpha.
\end{align*}\]</span></p>
<p><a href="#fig-twoSided" class="quarto-xref">Figure&nbsp;<span>6.1</span></a> shows an example of the rejection region for the case of a significance level <span class="math inline">\(\alpha=0.05\)</span> and <span class="math inline">\(n-K=12\)</span> degrees of freedom.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-twoSided" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-twoSided-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-Small-Sample-Inference_files/figure-html/fig-twoSided-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-twoSided-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.1: <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n-K=12\)</span> degrees of freedom and critical values <span class="math inline">\(c_{\alpha/2}=-2.18\)</span> and <span class="math inline">\(c_{1-\alpha/2}=2.18\)</span> for the significance level <span class="math inline">\(\alpha=0.05\)</span>.
</figcaption></figure>
</div>
</div>
</div>
<p>To find the <span class="math inline">\(c_{\alpha/2}\)</span> and <span class="math inline">\(c_{1-\alpha/2}\)</span> critical values we can use <code>R</code> as following:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">alpha</span> <span class="op">&lt;-</span> <span class="fl">0.05</span> <span class="co"># chosen signficance level </span></span>
<span><span class="va">df</span>    <span class="op">&lt;-</span> <span class="fl">12</span>   <span class="co"># degrees of freedom </span></span>
<span></span>
<span><span class="co">## Two-sided critical value (= (1-alpha/2) quantile):</span></span>
<span><span class="va">c_twoSided</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">qt</a></span><span class="op">(</span>p <span class="op">=</span> <span class="fl">1</span><span class="op">-</span><span class="va">alpha</span><span class="op">/</span><span class="fl">2</span>, df <span class="op">=</span> <span class="va">df</span><span class="op">)</span></span>
<span></span>
<span><span class="co">## lower critical value</span></span>
<span><span class="op">-</span><span class="va">c_twoSided</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.178813</code></pre>
</div>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## upper critical value</span></span>
<span><span class="va">c_twoSided</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.178813</code></pre>
</div>
</div>
</section><section id="rejection-regions-of-the-one-sided-t-test" class="level4" data-number="6.3.3.3"><h4 data-number="6.3.3.3" class="anchored" data-anchor-id="rejection-regions-of-the-one-sided-t-test">
<span class="header-section-number">6.3.3.3</span> Rejection Regions of the One-Sided <span class="math inline">\(t\)</span>-Test</h4>
<p>Possible one-sided hypothesis: <span class="math display">\[\begin{align*}
&amp;H_0: \beta_k \leq \beta_k^{(0)}\\
\text{versus}\quad
&amp; H_1: \beta_k &gt; \beta_k^{(0)}
\end{align*}\]</span></p>
<p>This is now slightly more involved since the null hypothesis is a <strong>compound hypothesis</strong>: <span class="math display">\[
H_0: \beta_k \in \;\big]-\infty,\beta_k^{(0)}\big]
\]</span></p>
<!-- To handle this issue, it is useful to state the **compound null hypothesis** as a family of *infinitely many* specific null hypotheses:
\begin{align*}
&H_0: \beta_k =\tilde\beta_k^{(0)}\quad\text{with}\quad \tilde\beta_k^{(0)}\in ]-\infty,\beta_k^{(0)}]\\
\text{versus}\quad 
& H_1: \beta_k > \beta_k^{(0)}
\end{align*} -->
<p>Of course, under the scenario that <span class="math inline">\(H_0\)</span> is true, <strong>only one</strong> of the infinitely many null hypotheses <strong>is actually true</strong> and all other null hypotheses are wrong.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>The idea of a <strong>compound null hypothesis</strong> <span class="math inline">\(H_0:\theta\in\Theta_0\)</span> is to collect all hypotheses which we do not care to detect by the statistical test. This way, the set of alternative hypotheses <span class="math inline">\(H_1:\theta\in\Theta_1\)</span> becomes smaller which leads to more powerful tests.</p>
</div>
</div>
<p>To conduct the <span class="math inline">\(t\)</span>-test we need to take one null hypothetical value <span class="math display">\[
\tilde\beta_k^{(0)}\in ]-\infty,\beta_k^{(0)}]
\]</span> which leads to a <span class="math inline">\(\tilde\beta_k^{(0)}\)</span> specific <span class="math inline">\(t\)</span>-test <span class="math display">\[\begin{align*}
T(\tilde\beta_k^{(0)}) :=
\frac{\hat\beta_k - \tilde\beta_k^{(0)}}{\widehat{SE}(\hat\beta_{k}|X)}
\end{align*}\]</span></p>
<p>Under Assumptions 1-4<span class="math inline">\(^\ast,\)</span> we have that <span id="eq-NullDistrOneSided"><span class="math display">\[
\begin{align*}
T(\tilde\beta_k^{(0)})
&amp;=
\frac{\hat\beta_k \overbrace{- \beta_k + \beta_k}^{=0} - \tilde\beta_k^{(0)}}{\widehat{SE}(\hat\beta_{k}|X)}\\[2ex]
&amp;=
\underbrace{\frac{\hat\beta_k - \beta_k}{\widehat{SE}(\hat\beta_{k}|X)}}_{\sim t_{(n-K)}} +
\underbrace{\frac{\beta_k - \tilde\beta_k^{(0)}}{\widehat{SE}(\hat\beta_{k}|X)}}_{❓},
\end{align*}
\qquad(6.6)\]</span></span> where under <span class="math inline">\(H_0:\beta_k \in ]-\infty,\beta_k^{(0)}].\)</span></p>
<p>The second term in <a href="#eq-NullDistrOneSided" class="quarto-xref">Equation&nbsp;<span>6.6</span></a> is challenging:</p>
<ul>
<li>Generally, this term is non-zero since the selected null hypothetical value <span class="math inline">\(\tilde{\beta}_k^{(0)}\)</span> generally does not equal the true (unknown) <span class="math inline">\(\beta_k.\)</span>
</li>
<li>If it is non-zero, we do not know its distribution.</li>
</ul>
<p><strong>Solution:</strong> Under <span class="math inline">\(H_0,\)</span> we know that <span class="math display">\[
\beta_k \leq \beta_k^{(0)}.
\]</span> Thus, when setting <span class="math display">\[
\tilde\beta_k^{(0)} = \beta_k^{(0)},
\]</span> for conducting the <span class="math inline">\(t\)</span>-test, we know, under <span class="math inline">\(H_0,\)</span> that <span id="eq-NullDistrOneSidedIneq"><span class="math display">\[
\begin{align*}
T(\beta_k^{(0)})
&amp;=
\frac{\hat\beta_k - \beta_k^{(0)}}{\widehat{SE}(\hat\beta_{k}|X)}\\[2ex]
&amp;=
\underbrace{\frac{\hat\beta_k - \beta_k}{\widehat{SE}(\hat\beta_{k}|X)}}_{\sim t_{(n-K)}} +
\underbrace{\frac{\beta_k - \beta_k^{(0)}}{\widehat{SE}(\hat\beta_{k}|X)}}_{{\color{darkgreen}\leq 0}}\\[2ex]
&amp;\leq
\frac{\hat\beta_k - \beta_k}{\widehat{SE}(\hat\beta_{k}|X)} \sim t_{(n-K)},
\end{align*}
\qquad(6.7)\]</span></span> where the inequality holds with probability one (i.e.&nbsp;for any possible realization).</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<!-- Under $H_0:\beta_k \leq \beta_k^{(0)}$ we can consider two cases: 
1. For $\beta_k = \beta_k^{(0)},$
$$
T(\beta_k^{(0)}) \sim t_{(n-K)} 
$$
2. For $\beta_k < \beta_k^{(0)},$ the distribution of $T(\beta_k^{(0)})$ is **strictly dominated** by the $t$-distribution with $(n-K)$ degrees of freedom.  -->
<p>Let <span class="math inline">\(F_{T(\beta_k^{(0)})}\)</span> and <span class="math inline">\(F_{t_{(n-K)}}\)</span> denote cumulative distribution functions of <span class="math inline">\(T(\beta_k^{(0)})\)</span> and of the <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\((n-K)\)</span> degrees of freedom.</p>
<p>The inequality in <a href="#eq-NullDistrOneSidedIneq" class="quarto-xref">Equation&nbsp;<span>6.7</span></a> implies that:</p>
<ol type="1">
<li>If <span class="math inline">\(\beta_k = \beta_k^{(0)},\)</span> the distribution of <span class="math inline">\(T(\beta_k^{(0)})\)</span> equals the <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\((n-K)\)</span> degrees of freedom, i.e. <span class="math display">\[\begin{align*}
T(\beta_k^{(0)}) &amp;\sim t_{(n-K)}\\[2ex]
\Leftrightarrow \; F_{T(\beta_k^{(0)})} (x) &amp;= F_{t_{(n-K)}}(x) \quad\text{for all}\quad x\in\mathbb{R}
\end{align*}\]</span>
</li>
<li>If <span class="math inline">\(\beta_k &lt; \beta_k^{(0)},\)</span> the distribution of <span class="math inline">\(T(\beta_k^{(0)})\)</span> is <strong>strictly dominated</strong> by the <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\((n-K)\)</span> degrees of freedom, i.e. <span class="math display">\[
F_{T(\beta_k^{(0)})} (x) &gt; F_{t_{(n-K)}}(x) \quad\text{for all}\quad x\in\mathbb{R}.
\]</span>
</li>
</ol>
</div>
</div>
<p>Therefore, we can use the <span class="math inline">\((1-\alpha)\)</span>-quantile of the <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\((n-K)\)</span> degrees of freedom, <span class="math inline">\(c_{1-\alpha},\)</span> to define the rejection region <span class="math display">\[
\mathcal{R} = ]c_{1-\alpha},\infty[,
\]</span> since this allows us to control the size simultaneously for all (infinitely many) null hypotheses <span class="math inline">\(H_0:\beta_k \leq \beta_k^{(0)},\)</span> <span class="math display">\[
\text{Size}=\sup_{\beta_k \in ]-\infty,\beta_k^{(0)}]}P(T(\beta_k^{(0)}) \in\mathcal{R}) = \alpha.
\]</span></p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>The inequality in <a href="#eq-NullDistrOneSidedIneq" class="quarto-xref">Equation&nbsp;<span>6.7</span></a> implies that <span class="math display">\[
P(T(\beta_k^{(0)}) \in\mathcal{R}) = \alpha
\quad\text{if}\quad
\beta_k = \beta_k^{(0)}
\]</span> and that <span class="math display">\[
P(T(\beta_k^{(0)}) \in\mathcal{R}) &lt; \alpha
\quad\text{if}\quad
\beta_k &lt; \beta_k^{(0)}.
\]</span></p>
</div>
</div>
<p>Thus, for testing <span class="math display">\[\begin{align*}
&amp;H_0: \beta_k \leq \beta_k^{(0)}\\
\text{versus}\quad
&amp; H_1: \beta_k &gt;    \beta_k^{(0)}\\
\end{align*}\]</span> the rejection region is <span class="math display">\[
\mathcal{R}=\;]c_{1-\alpha}, \infty[
\]</span></p>
<ul>
<li>We can reject <span class="math inline">\(H_0\)</span> if <span class="math display">\[\begin{align*}
T_{obs}
&amp; \in \mathcal{R} = \;]c_{1-\alpha}, \infty[
\end{align*}\]</span>
</li>
<li>We cannot reject <span class="math inline">\(H_0\)</span> if <span class="math display">\[\begin{align*}
T_{obs}
&amp;\not \in \mathcal{R} = \;]c_{1-\alpha}, \infty[
\end{align*}\]</span>
</li>
</ul>
<p><a href="#fig-oneSidedRight" class="quarto-xref">Figure&nbsp;<span>6.2</span></a> shows an example of the rejection region for the case of a significance level <span class="math inline">\(\alpha=0.05\)</span> and <span class="math inline">\(n-K=12\)</span> degrees of freedom.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-oneSidedRight" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-oneSidedRight-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-Small-Sample-Inference_files/figure-html/fig-oneSidedRight-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-oneSidedRight-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.2: <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n-K=12\)</span> degrees of freedom and critical value <span class="math inline">\(c_{1-\alpha}=1.78\)</span> for the significance level <span class="math inline">\(\alpha=0.05\)</span>.
</figcaption></figure>
</div>
</div>
</div>
<p>To find the <span class="math inline">\(c_{1-\alpha}\)</span> critical value we can use <code>R</code> as following:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">alpha</span> <span class="op">&lt;-</span> <span class="fl">0.05</span> <span class="co"># chosen significance level </span></span>
<span><span class="va">df</span>    <span class="op">&lt;-</span> <span class="fl">12</span>   <span class="co"># degrees of freedom </span></span>
<span></span>
<span><span class="co">## One-sided critical value (1-alpha) quantile:</span></span>
<span><span class="va">c_oneSided</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">qt</a></span><span class="op">(</span>p <span class="op">=</span> <span class="fl">1</span><span class="op">-</span><span class="va">alpha</span>, df <span class="op">=</span> <span class="va">df</span><span class="op">)</span></span>
<span><span class="va">c_oneSided</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.782288</code></pre>
</div>
</div>
<p>By equivalent arguments, we can also do a one-sided <span class="math inline">\(t\)</span>-test for the “other side.”</p>
<p>For testing <span class="math display">\[\begin{align*}
&amp;H_0:  \beta_k \geq \beta_k^{(0)}\\
\text{versus}\quad
&amp;H_1:  \beta_k &lt;  \beta_k^{(0)}\\
\end{align*}\]</span> the rejection region is <span class="math display">\[
\mathcal{R}=\;]-\infty,c_{\alpha}[
\]</span></p>
<ul>
<li>We can reject <span class="math inline">\(H_0\)</span> if <span class="math display">\[\begin{align*}
T_{obs}
&amp; \in \mathcal{R} = \;]-\infty,c_{\alpha}[
\end{align*}\]</span>
</li>
<li>We cannot reject <span class="math inline">\(H_0\)</span> if <span class="math display">\[\begin{align*}
T_{obs}
&amp;\not \in \mathcal{R} = \;]-\infty,c_{\alpha}[
\end{align*}\]</span>
</li>
</ul>
<p><a href="#fig-oneSidedLeft" class="quarto-xref">Figure&nbsp;<span>6.3</span></a> shows an example of the rejection region for the case of a significance level <span class="math inline">\(\alpha=0.05\)</span> and <span class="math inline">\(n-K=12\)</span> degrees of freedom.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-oneSidedLeft" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-oneSidedLeft-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-Small-Sample-Inference_files/figure-html/fig-oneSidedLeft-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-oneSidedLeft-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.3: <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n-K=12\)</span> degrees of freedom and critical value <span class="math inline">\(c_{\alpha}=-1.78\)</span> for the significance level <span class="math inline">\(\alpha=0.05\)</span>.
</figcaption></figure>
</div>
</div>
</div>
<p>To find the <span class="math inline">\(c_{\alpha}\)</span> critical value we can use <code>R</code> as following:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">alpha</span> <span class="op">&lt;-</span> <span class="fl">0.05</span> <span class="co"># chosen significance level </span></span>
<span><span class="va">df</span>    <span class="op">&lt;-</span> <span class="fl">12</span>   <span class="co"># degrees of freedom </span></span>
<span></span>
<span><span class="co">## One-sided critical value (alpha) quantile:</span></span>
<span><span class="va">c_oneSided</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">qt</a></span><span class="op">(</span>p <span class="op">=</span> <span class="va">alpha</span>, df <span class="op">=</span> <span class="va">df</span><span class="op">)</span></span>
<span><span class="va">c_oneSided</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.782288</code></pre>
</div>
</div>
</section></section><section id="power-1" class="level3" data-number="6.3.4"><h3 data-number="6.3.4" class="anchored" data-anchor-id="power-1">
<span class="header-section-number">6.3.4</span> Power</h3>
<!-- A type-II-error is the mistake of not rejecting the null hypothesis when in fact it should have been rejected. The probability of making a type-II-error equals one minus the probability of correctly rejecting the null hypothesis ("Power").  -->
<!-- For instance, in the case of using the $t$-test to test the null hypothesis $H_0: \beta_k=0$ versus the one-sided alternative hypothesis $H_1:\beta_k>0$) we have that 
\begin{align*}
P(\text{type-II-error})
&=P_{H_1}\Big(t\;\in\;\overbrace{]-\infty,c_{1-\alpha}]}^{\text{non-rejection region}}\Big)\\
&=1-\underbrace{P_{H_1}\Big(t\;\in\;\overbrace{]c_{1-\alpha},\infty[}^{\text{rejection region}}\Big)}_{\text{"Power"}},
\end{align*}
where $P_{H_1}$ means that we compute the probability under the assumption that $H_1$ is true.  -->
<!-- 
::: {.callout-note}
There is a trade off between the probability of making a type-I-error and the probability of making a type-II-error: a lower significance level $\alpha$ decreases $P(\text{type-I-error})$, but necessarily increases $P(\text{type-II-error})$ and vice versa.  
Ideally, we would have some sense of the costs of making each of these errors, and would choose our significance level to minimize these total costs. However, the costs are often difficult to know.  
:::  
-->
<p>Since we want to detect violations of the null-hypothesis, we want that our test has a large power <span class="math display">\[\begin{align*}
\text{Power}
&amp; = 1 - P(\text{type-II-error})\\[2ex]
&amp; = 1 - P(\text{Not reject $H_0$ given $H_1$ is true})\\[2ex]
&amp; = P(\text{Reject $H_0$ given $H_1$ is true})\\[2ex]
&amp; = P(\text{Detect a true violation of the null})
\end{align*}\]</span></p>
<p>Unfortunately, computing the power of a statistical test is usually impossible, since this requires knowing the distribution of the test statistic under the alternative hypothesis <span class="math inline">\(H_1.\)</span> The distribution of a test statistic under <span class="math inline">\(H_1\)</span> can only be derived under quite restrictive setups.</p>
<p>In the following, we consider such a restrictive setup for the <span class="math inline">\(t\)</span>-test statistic.</p>
<p>Let’s consider the one-sided hypothesis <span class="math display">\[\begin{align*}
&amp;H_0: \beta_k\leq \beta_{k}^{(0)}\\
&amp;H_1: \beta_k &gt; \beta_{k}^{(0)}
\end{align*}\]</span></p>
<ul>
<li>let <span class="math inline">\(X\)</span> be deterministic such that <span class="math inline">\(T|X \overset{d}{=}T\)</span> and</li>
<li>let the true standard error of <span class="math inline">\(\hat\beta_k\)</span> be<br><span class="math display">\[
\operatorname{SE}(\hat\beta_k|X)=\frac{1}{\sqrt{n}}4.5.
\]</span>
</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Standard error of <span class="math inline">\(\hat\beta_k\)</span> is proportional to <span class="math inline">\(1/\sqrt{n}\)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Of course, usually we do not know the standard error of the estimator, but have to estimate it. But it is true that the standard error of the OLS estimator <span class="math inline">\(\hat{\beta}_k\)</span> is <strong>proportional to</strong> <span class="math inline">\(1/\sqrt{n},\)</span> <span class="math display">\[
\operatorname{SE}(\hat\beta_k|X) = \frac{1}{\sqrt{n}}\cdot \texttt{constant},
\]</span> where the <span class="math inline">\(\texttt{constant}\)</span> may depend on <span class="math inline">\(X,\)</span> but not on <span class="math inline">\(n.\)</span></p>
</div>
</div>
<p>Under this setup and under Assumptions 1-4^<span class="math inline">\(\ast,\)</span> the <span class="math inline">\(t\)</span>-test statistic is <strong>normally distributed</strong>.</p>
<p>If <span class="math inline">\(H_0\)</span> is true with <span class="math inline">\(\beta_k=\beta_k^{(0)},\)</span> then <span class="math display">\[\begin{align*}
T
&amp;=\frac{\hat\beta_k-\beta_k^{(0)}}{\frac{1}{\sqrt{n}}4.5}\\[2ex]
&amp;=\frac{\sqrt{n}(\hat\beta_k-\beta_k)}{4.5} \sim \mathcal{N}(0,1).
\end{align*}\]</span></p>
<p><strong>Note:</strong> It suffices to look at this specific null hypothesis <span class="math inline">\(\beta_k=\beta_k^{(0)},\)</span> since the distribution of <span class="math inline">\(T\)</span> is dominated by <span class="math inline">\(\mathcal{N}(0,1)\)</span> for all other null hypotheses <span class="math inline">\(\beta_k&lt;\beta_k^{(0)};\)</span> see our discussions above.</p>
<p>If <span class="math inline">\(H_1: \beta_k-\beta_k^{(0)}&gt;0\)</span> is true, then <span class="math display">\[\begin{align*}
T&amp;=\frac{\hat\beta_k-\beta_k^{(0)}}{\frac{1}{\sqrt{n}}4.5}
=\frac{\hat\beta_k\overbrace{-\beta_k+\beta_k}^{=0}-\beta_k^{(0)}}{\frac{1}{\sqrt{n}}4.5}\\[2ex]
&amp;=\underbrace{\frac{\sqrt{n}(\hat\beta_k-\beta_k)}{4.5}}_{\sim \mathcal{N}(0,1)}+\underbrace{\frac{\sqrt{n}(\beta_k-\beta_k^{(0)})}{4.5}}_{=\text{mean-shift}}\\[2ex]
&amp;\sim \mathcal{N}\left(\frac{\sqrt{n}(\beta_k-\beta_k^{(0)})}{4.5},1\right)
\end{align*}\]</span></p>
<p>Power: <span class="math display">\[\begin{align*}
\text{Power}
&amp; = P(\text{Reject $H_0$ given $H_1$ is true})\\[2ex]
%&amp; = P(T \in \left]z_{1-\alpha},\infty\right[ \;\;|\; H_1\text{ is true})\\[2ex]
&amp; = P(T &gt; z_{1-\alpha}\;|\; H_1\text{ is true}),
\end{align*}\]</span> where <span class="math inline">\(z_{1-\alpha}\)</span> denotes the <span class="math inline">\((1-\alpha)\)</span> quantile of the standard normal distribution <span class="math inline">\(\mathcal{N}(0,1),\)</span> and where <span class="math display">\[
T\sim \mathcal{N}\left(\frac{\sqrt{n}(\beta_k-\beta_k^{(0)})}{4.5},1\right).
\]</span></p>
<p>This allows us to compute the power as following: <span class="math display">\[\begin{align*}
\text{Power}
&amp; = P(T &gt; z_{1-\alpha}\;|\; H_1\text{ is true}),
\\[2ex]
&amp; = P\Bigg(\overbrace{T - \frac{\sqrt{n}(\beta_k-\beta_k^{(0)})}{4.5}}^{=Z\sim\mathcal{N}(0,1)} &gt; z_{1-\alpha} - \frac{\sqrt{n}(\beta_k-\beta_k^{(0)})}{4.5}\Bigg)\\[2ex]
&amp; = P\left(Z &gt; z_{1-\alpha} - \frac{\sqrt{n}(\beta_k-\beta_k^{(0)})}{4.5}\right)\\[2ex]%,\quad\text{where}\quad Z\sim\mathcal{N}(0,1)\\[2ex]
&amp;=1-P\left(Z \leq z_{1-\alpha} - \frac{\sqrt{n}(\beta_k-\beta_k^{(0)})}{4.5}\right)\\[2ex]
&amp;=1-\Phi\left(z_{1-\alpha} - \frac{\sqrt{n}(\beta_k-\beta_k^{(0)})}{4.5}\right),
\end{align*}\]</span> where <span class="math inline">\(\Phi\)</span> denotes the cumulative distribution function of the standard normal distribution <span class="math inline">\(\mathcal{N}(0,1).\)</span></p>
<p><a href="#fig-Power" class="quarto-xref">Figure&nbsp;<span>6.4</span></a> illustrates the probability of a type-II-error and the power for the case where</p>
<ul>
<li><span class="math inline">\(\alpha = 0.05\)</span></li>
<li><span class="math inline">\(n=9\)</span></li>
<li><span class="math inline">\(\beta_k - \beta_k^{(0)}=3\)</span></li>
</ul>
<p>such that <span class="math display">\[\begin{align*}
\text{Power}
&amp;=1-\Phi\Bigg(z_{1-\alpha} - \overbrace{\frac{\sqrt{n}(\beta_k-\beta_k^{(0)})}{4.5}}^{=\frac{3\cdot 3}{4.5} = 2}\Bigg)\\[2ex]
&amp;=1-\Phi\left(1.64  - 2 \right)\\[2ex]
&amp;=1-0.359=0.641
\end{align*}\]</span> That is, we expect to detect the violation of the null hypothesis <span class="math inline">\((\beta_k - \beta_k^{(0)}=3)\)</span> in <span class="math inline">\(64\%\)</span> of resamplings from the random sample (data generating process).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-Power" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-Power-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-Small-Sample-Inference_files/figure-html/fig-Power-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-Power-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.4: Probability of a type-II-error and the power for a one-sided <span class="math inline">\(t\)</span>-test at significance level <span class="math inline">\(\alpha = 0.05,\)</span> sample size <span class="math inline">\(n=9,\)</span> and violation of the null hypothesis <span class="math inline">\(\beta_k - \beta_k^{(0)}=3.\)</span>
</figcaption></figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Power is a function of <span class="math inline">\(\alpha,\)</span> <span class="math inline">\((\beta_k-\beta_k^{(0)}),\)</span> and <span class="math inline">\(n\)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<!-- Thus, the power of the $t$-test statistic is a function of 

* the significance level $\alpha$
* the violation of $H_0$, $(\beta_k-\beta_k^{(0)})>0$
* the sample size $n$ -->
<!-- \begin{align*}
\text{Power}(\alpha, (\beta_k-\beta_k^{(0)}), \sqrt{n})
&=1-\Phi\left(z_{1-\alpha} - \frac{\sqrt{n}(\beta_k-\beta_k^{(0)})}{4.5}\right),
\end{align*} -->
<p>Indeed, for all reasonable test statistics we have that: <span class="math display">\[\begin{align*}
%&amp;\text{One-Sided $H_1:\beta_k&gt;\beta_k^{(0)}$:}\\
%&amp;\text{Power}\left(\alpha, (\beta_k-\beta_k^{(0)}), \sqrt{n}\right)
%\to 1 \quad \text{as}\quad (\beta_k-\beta_k^{(0)})\to\infty\\[2ex]
%&amp;\text{One-Sided $H_1:\beta_k&lt;\beta_k^{(0)}$:}\\
%&amp;\text{Power}\left(\alpha, (\beta_k-\beta_k^{(0)}), \sqrt{n}\right)
%\to 1 \quad \text{as}\quad (\beta_k-\beta_k^{(0)})\to-\infty\\[2ex]
&amp;\text{Two-Sided $H_1:\beta_k\neq\beta_k^{(0)}$:}\\
&amp;\text{Power}\left(\alpha, (\beta_k-\beta_k^{(0)}), \sqrt{n}\right)
\to 1 \quad \text{as}\quad |\beta_k-\beta_k^{(0)}|\to\infty\\[2ex]
&amp;\text{Power}\left(\alpha, (\beta_k-\beta_k^{(0)}), \sqrt{n}\right)
\to 1 \quad \text{as}\quad n\to\infty\\[2ex]
&amp;\text{Power}\left(\alpha, (\beta_k-\beta_k^{(0)}), \sqrt{n}\right)
\to 0 \quad \text{as}\quad \alpha\to 0
\end{align*}\]</span> <!-- when keeping each of the other arguments fixed.  --></p>
</div>
</div>
</section><section id="sec-pValue" class="level3" data-number="6.3.5"><h3 data-number="6.3.5" class="anchored" data-anchor-id="sec-pValue">
<span class="header-section-number">6.3.5</span> <span class="math inline">\(p\)</span>-Value</h3>
<section id="f-test" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="f-test">
<span class="math inline">\(F\)</span>-Test</h4>
<p>The <span class="math inline">\(F\)</span>-test allows us to test <span class="math display">\[
\begin{align*}
&amp;H_0: R\beta = r\\[2ex]
\text{versus}\quad
&amp;H_1: R\beta\neq r,
\end{align*}
\]</span> where <span class="math inline">\(\beta\)</span> denotes the true (unknown) parameter vector and <span class="math inline">\(r^{(0)}\)</span> the null-hypothetical value specified by the statistician (often, e.g.&nbsp;<span class="math inline">\(r^{(0)}=0\)</span>).</p>
<p>We know that <span class="math display">\[
F\overset{H_0}{\sim}F_{q,n-K}.
\]</span></p>
<p>The <span class="math inline">\(p\)</span>-value of the <span class="math inline">\(F\)</span>-test is the probability of seeing realizations of <span class="math inline">\(F\)</span> that are equal to or larger than the observed value <span class="math inline">\(F_{\text{obs}}\)</span> given that the null hypothesis is true <span class="math display">\[
p_{\text{obs}}=P(F\geq F_{\text{obs}}\;|\;H_0 \text{ is true})
\]</span></p>
<ul>
<li><p>We reject the null hypothesis <span class="math inline">\(H_0\)</span> if <span class="math display">\[
p_{\text{obs}} &lt; \alpha
\]</span></p></li>
<li><p>We cannot reject the null hypothesis <span class="math inline">\(H_0\)</span> if <span class="math display">\[
p_{\text{obs}} \geq \alpha
\]</span></p></li>
</ul></section><section id="the-one-sided-t-test" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="the-one-sided-t-test">The One-Sided <span class="math inline">\(t\)</span>-Test</h4>
<p>Possible one-sided hypotheses:</p>
<p><span class="math display">\[\begin{align*}
&amp;H_0: \beta_k \leq \beta_k^{(0)}\\
\text{versus}\quad &amp; H_1:\beta_k &gt;    \beta_k^{(0)}\\
\end{align*}\]</span></p>
<p>or</p>
<p><span class="math display">\[\begin{align*}
&amp;H_0: \beta_k \geq \beta_k^{(0)}\\
\text{versus}\quad &amp; H_1: \beta_k &lt;  \beta_k^{(0)}\\
\end{align*}\]</span></p>
<!-- In case of a one-sided $t$-test, we will reject the null if $T_{\text{obs}}$ is sufficiently "far away" from zero in the relevant direction of $H_1$.  -->
<p>We know that <span class="math display">\[
T\overset{H_0}{\sim}t_{n-K}.
\]</span></p>
<p>The <span class="math inline">\(p\)</span>-value of the one-sided <span class="math inline">\(t\)</span>-test for testing <span class="math display">\[\begin{align*}
&amp;H_0: \beta_k \leq \beta_k^{(0)}\\
\text{versus}\quad &amp; H_1: \beta_k &gt;    \beta_k^{(0)}\\
\end{align*}\]</span> is the probability of seeing realizations of <span class="math inline">\(T\)</span> that are equal to or larger than the observed value <span class="math inline">\(T_{\text{obs}}\)</span> given that the null hypothesis is true <span class="math display">\[
p_{\text{obs}}=P(T\geq T_{\text{obs}}\;|\;H_0 \text{ is true}).
\]</span> * We reject the null hypothesis <span class="math inline">\(H_0\)</span> if <span class="math display">\[
p_{\text{obs}} &lt; \alpha
\]</span></p>
<ul>
<li>We cannot reject the null hypothesis <span class="math inline">\(H_0\)</span> if <span class="math display">\[
p_{\text{obs}} \geq \alpha
\]</span>
</li>
</ul>
<p>The <span class="math inline">\(p\)</span>-value of the one-sided <span class="math inline">\(t\)</span>-test for testing <span class="math display">\[\begin{align*}
&amp;H_0: \beta_k \geq \beta_k^{(0)}\\
\text{versus}\quad &amp; H_1: \beta_k &lt;    \beta_k^{(0)}\\
\end{align*}\]</span> is the probability of seeing realizations of <span class="math inline">\(T\)</span> that are equal to or smaller than the observed value <span class="math inline">\(T_{\text{obs}}\)</span> given that the null hypothesis is true <span class="math display">\[
p_{\text{obs}}=P(T\leq T_{\text{obs}}\;|\;H_0 \text{ is true}).
\]</span></p>
<ul>
<li><p>We reject the null hypothesis <span class="math inline">\(H_0\)</span> if <span class="math display">\[
p_{\text{obs}} &lt; \alpha
\]</span></p></li>
<li><p>We cannot reject the null hypothesis <span class="math inline">\(H_0\)</span> if <span class="math display">\[
p_{\text{obs}} \geq \alpha
\]</span></p></li>
</ul></section><section id="the-two-sided-t-test" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="the-two-sided-t-test">The Two-Sided <span class="math inline">\(t\)</span>-Test</h4>
<p>The two-sided <span class="math inline">\(t\)</span>-test allows us to test <span class="math display">\[\begin{align*}
&amp; H_0: \beta_k=\beta_k^{(0)}\\
\text{versus}\quad
&amp; H_1: \beta_k\ne \beta_k^{(0)}
\end{align*}\]</span> where <span class="math inline">\(\beta_k\)</span> denotes the true (unknown) parameter value and <span class="math inline">\(\beta_k^{(0)}\)</span> the null hypothetical value specified by the statisticaian (e.g.&nbsp;<span class="math inline">\(\beta_k^{(0)}=0\)</span>).</p>
<p>We know that <span class="math display">\[
T\overset{H_0}{\sim}t_{n-K}.
\]</span></p>
<p>The <span class="math inline">\(p\)</span>-value of the two-sided <span class="math inline">\(t\)</span>-test is the probability of seeing realizations of <span class="math inline">\(T\)</span> that are equal to or more extreme than the observed value <span class="math inline">\(T_{\text{obs}}\)</span> given that the null hypothesis is true <span class="math display">\[\begin{align*}
p_{\text{obs}}
&amp;=P(|T|\geq |T_{\text{obs}}|\;|\;H_0 \text{ is true})\\[2ex]
&amp;=2\cdot\min\{P(T\leq T_{\text{obs}}\;|\;H_0 \text{ is true}),
            P(T\geq T_{\text{obs}}\;|\;H_0 \text{ is true})\}
\end{align*}\]</span></p>
<ul>
<li><p>We reject the null hypothesis <span class="math inline">\(H_0\)</span> if <span class="math display">\[
p_{\text{obs}} &lt; \alpha
\]</span></p></li>
<li><p>We cannot reject the null hypothesis <span class="math inline">\(H_0\)</span> if <span class="math display">\[
p_{\text{obs}} \geq \alpha
\]</span></p></li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Marginal Significance Value
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <span class="math inline">\(p\)</span>-value equals the significance level <span class="math inline">\(\alpha\)</span> for which we just fail to reject the null. Therefore, the <span class="math inline">\(p\)</span>-value is sometimes also called “marginal significance value”.</p>
</div>
</div>
<!-- The $p$-value of a test statistic is the significance level we would obtain if we took the sample value of the observed test statistic, $F_{\text{obs}}$ or $t_{\text{obs}},$ as the border between the rejection and non-rejection regions. 

* **$F$-test:** 
* **$t$-test:** 
   * Two sided, i.e.,  $H_0:\beta_k = r$ vs. $H_1:\beta_k\neq r$: <br> 
    $p=2\cdot\min\{P_{H_0}(t\leq t_{\text{obs}}),P_{H_0}(t\geq t_{\text{obs}})\}=P_{H_0}(|t|\geq|t_{\text{obs}}|)$ <br>
    The latter equality holds since the $t$ distrbution is symmetric. 
   * One sided, i.e., $H_0:\beta_k \leq r$ vs. $H_1:\beta_k> r$: <br> 
     $p=P_{H_0}(t\geq t_{\text{obs}})$
   * One sided, i.e., $H_0:\beta_k \geq r$ vs. $H_1:\beta_k< r$: <br> 
     $p=P_{H_0}(t\leq t_{\text{obs}})$



If the $p$-value is strictly smaller than the chosen significance level $\alpha$, we reject the null hypothesis.  -->
</section></section></section><section id="sec-CIsmallsample" class="level2" data-number="6.4"><h2 data-number="6.4" class="anchored" data-anchor-id="sec-CIsmallsample">
<span class="header-section-number">6.4</span> Confidence Intervals</h2>
<p>We define a two-sided <span class="math inline">\((1-\alpha)\cdot 100\%\)</span> percent confidence interval for the <em>deterministic</em> (unknown) true <span class="math inline">\(\beta_k\)</span> as the <strong>random interval</strong> <span class="math inline">\(\operatorname{CI}_{k,1-\alpha}\)</span> for which <span class="math display">\[
P\Big(\beta_k\in\operatorname{CI}_{k,1-\alpha}\Big)\geq 1-\alpha.
\]</span> Derivation of the random interval <span class="math inline">\(\operatorname{CI}_{k,1-\alpha}\)</span>:</p>
<p>Observe that (under Ass 1-4<span class="math inline">\(^\ast\)</span>) <span id="eq-CIDistr"><span class="math display">\[
\frac{\hat\beta_k-\beta_k}{\widehat{\operatorname{SE}}(\hat\beta_k|X)}\sim t_{(n-K)}
\qquad(6.8)\]</span></span> Therefore, <span class="math display">\[\begin{align*}
P\left(-c_{1-\alpha/2}\leq\frac{\hat\beta_k-\beta_k}{\widehat{\operatorname{SE}}(\hat\beta_k|X)}\leq c_{1-\alpha/2}\right)=1-\alpha,
\end{align*}\]</span> where <span class="math inline">\(c_{1-\alpha/2}\)</span> denotes the <span class="math inline">\((1-\alpha/2)\)</span> quantile of the <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\((n-K)\)</span> degrees of freedom. Next, we can do the following equivalent transformations <span class="math display">\[\begin{align*}
P\left(-c_{1-\alpha/2}\leq\frac{\hat\beta_k-\beta_k}{\widehat{\operatorname{SE}}(\hat\beta_k|X)}\leq c_{1-\alpha/2}\right)&amp;=1-\alpha\\
\Leftrightarrow P\left(\hat\beta_k-c_{1-\alpha/2}\widehat{\operatorname{SE}}(\hat\beta_k|X)\leq \beta_k\leq\hat\beta_k +c_{1-\alpha/2}\widehat{\operatorname{SE}}(\hat\beta_k|X)\right)&amp;=1-\alpha\\
\Leftrightarrow P\left(\beta_k\in\underbrace{\left[\hat\beta_k-c_{1-\alpha/2}\widehat{\operatorname{SE}}(\hat\beta_k|X),\;\hat\beta_k +c_{1-\alpha/2}\widehat{\operatorname{SE}}(\hat\beta_k|X)\right]}_{=:\operatorname{CI}_{k,1-\alpha}}\right)&amp;=1-\alpha
\end{align*}\]</span> That is, the random interval <span class="math display">\[
\operatorname{CI}_{k,1-\alpha}=\left[\hat\beta_k-c_{1-\alpha/2}\widehat{\operatorname{SE}}(\hat\beta_k|X),\;\hat\beta_k + c_{1-\alpha/2}\widehat{\operatorname{SE}}(\hat\beta_k|X)\right]
\]</span> is our <span class="math inline">\((1-\alpha)\cdot 100\%\)</span> confidence interval for <span class="math inline">\(\beta_k\)</span>.</p>
<p>Since the confidence interval is based on the exact distribution (under Assumptions 1-4<span class="math inline">\(^\ast\)</span>) in <a href="#eq-CIDistr" class="quarto-xref">Equation&nbsp;<span>6.8</span></a>, the confidence interval has an <strong>exact</strong> coverage probability <span class="math display">\[\begin{align*}
P\left(\beta_k\in\operatorname{CI}_{k,1-\alpha}\right)&amp;=1-\alpha
\end{align*}\]</span> provided the Assumptions 1-4<span class="math inline">\(^\ast\)</span> are true.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Interpretation of Confidence Intervals
</div>
</div>
<div class="callout-body-container callout-body">
<p>The random interval <span class="math inline">\(\operatorname{CI}_{k,1-\alpha}\)</span> for <span class="math inline">\(\beta_k\)</span> contains the true parameter value <span class="math inline">\(\beta_k\)</span> with probability <span class="math inline">\(1-\alpha;\)</span> i.e.&nbsp;we expect that <span class="math inline">\(\operatorname{CI}_{k,1-\alpha}\)</span> covers <span class="math inline">\(\beta_k\)</span> in <span class="math inline">\((1-\alpha)\cdot 100\%\)</span> of resamplings from the random sample.</p>
<p>It’s best to take a look at dynamic visualizations like this one:</p>
<center>
<a href="https://rpsychologist.com/d3/ci/">https://rpsychologist.com/d3/ci/</a>
</center>
<p>Unfortunately, this “frequentist” interpretation is not a statement about a single given <span class="math inline">\(\operatorname{CI}_{k,1-\alpha}\)</span> realization computed for a given data set. A given, realized <span class="math inline">\(\operatorname{CI}_{k,1-\alpha}\)</span> will either contain the true parameter <span class="math inline">\(\beta_k\)</span> or not, and usually we do not know the answer. So, confidence intervals are quite hard to interpret. However, they are very well suited as a tool to visualize estimation uncertainties in different parameter estimators, for instance, across <span class="math inline">\(\hat\beta_k\)</span>, <span class="math inline">\(k=1,\dots,K\)</span>.</p>
<center>
<img src="images/Meme_CI_2.jpg" class="img-fluid">
</center>
</div>
</div>
</section><section id="sec-PSSI" class="level2" data-number="6.5"><h2 data-number="6.5" class="anchored" data-anchor-id="sec-PSSI">
<span class="header-section-number">6.5</span> Monte Carlo Simulations</h2>
<p>Let’s check the above exact inference results using Monte Carlo simulations. The check, of course, applies only to the considered special case and generally does not generalize to other data generating processes.</p>
<p>First, we program a function <code>myDataGenerator()</code> which allows us to generate data from the following model, i.e., from the following fully specified data generating process: <span class="math display">\[\begin{align*}
Y_i &amp;=\beta_1+\beta_2X_{i2}+\beta_3X_{i3}+\varepsilon_i,\qquad i=1,\dots,n\\
\beta &amp;=(\beta_1,\beta_2,\beta_3)'=(2,3,4)'\\
X_{i2}&amp;\sim U[2,10]\\
X_{i3}&amp;\sim U[12,22]\\
\varepsilon_i|X&amp;\sim\mathcal{N}(0,3^2),
\end{align*}\]</span> where <span class="math inline">\((Y_i,X_i)\)</span> is i.i.d. across <span class="math inline">\(i=1,\dots,n\)</span>.</p>
<p>Let us consider a small sample size of <span class="math inline">\(n=7\)</span>.</p>
<p>The below function <code>myDataGenerator()</code> allows to sample new realizations of the random sample <span class="math display">\[
((X_1,Y_1),\dots,(X_n,Y_n))
\]</span> You can provide your own values for the sample size <span class="math inline">\(n\)</span> and for the parameter vector <span class="math inline">\(\beta=(\beta_1,\beta_2,\beta_3)'\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## Function to generate artificial data</span></span>
<span><span class="co">## If the user provides 'X_cond' data, </span></span>
<span><span class="co">## the sampling of new Y variables is </span></span>
<span><span class="co">## conditionally on the given X_cond variables.</span></span>
<span><span class="co">## If X_cond = NULL, sampling is done unconditionally. </span></span>
<span></span>
<span><span class="va">myDataGenerator</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">n</span>, <span class="va">beta</span><span class="op">)</span><span class="op">{</span></span>
<span></span>
<span><span class="co">## sampling predictors X:</span></span>
<span><span class="va">X</span>   <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">1</span>, <span class="va">n</span><span class="op">)</span>, </span>
<span>            <span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="va">n</span>, <span class="fl">2</span>, <span class="fl">10</span><span class="op">)</span>, </span>
<span>            <span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="va">n</span>,<span class="fl">12</span>, <span class="fl">22</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">## sampling error terms: </span></span>
<span><span class="va">eps</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">n</span>, sd <span class="op">=</span> <span class="fl">3</span><span class="op">)</span></span>
<span><span class="co">## generate realizations of Y:</span></span>
<span><span class="va">Y</span>    <span class="op">&lt;-</span> <span class="va">X</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="va">beta</span> <span class="op">+</span> <span class="va">eps</span></span>
<span><span class="co">## safe X and Y as a data frame:</span></span>
<span><span class="va">data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="st">"Y"</span>   <span class="op">=</span> <span class="va">Y</span>, </span>
<span>                   <span class="st">"X_1"</span> <span class="op">=</span> <span class="va">X</span><span class="op">[</span>,<span class="fl">1</span><span class="op">]</span>, </span>
<span>                   <span class="st">"X_2"</span> <span class="op">=</span> <span class="va">X</span><span class="op">[</span>,<span class="fl">2</span><span class="op">]</span>, </span>
<span>                   <span class="st">"X_3"</span> <span class="op">=</span> <span class="va">X</span><span class="op">[</span>,<span class="fl">3</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="co">## return the data frame</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span><span class="op">(</span><span class="va">data</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="co">## Small sample size</span></span>
<span><span class="va">n</span>             <span class="op">&lt;-</span> <span class="fl">7</span>        </span>
<span></span>
<span><span class="co">## Define the true beta vector</span></span>
<span><span class="va">beta_true</span>     <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>,<span class="fl">3</span>,<span class="fl">4</span><span class="op">)</span></span>
<span></span>
<span><span class="co">## Generate Y and X data </span></span>
<span><span class="va">test_data</span>     <span class="op">&lt;-</span> <span class="fu">myDataGenerator</span><span class="op">(</span>n <span class="op">=</span> <span class="va">n</span>, beta<span class="op">=</span><span class="va">beta_true</span><span class="op">)</span></span>
<span></span>
<span><span class="co">## Look at the first six lines of the data frame</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">test_data</span>,     <span class="fl">3</span><span class="op">)</span>, <span class="fl">2</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Y X_1  X_2   X_3
1 97.53   1 4.23 20.50
2 75.37   1 8.06 12.35
3 70.92   1 4.70 14.95</code></pre>
</div>
</div>
<section id="check-testing-multiple-parameters" class="level3" data-number="6.5.1"><h3 data-number="6.5.1" class="anchored" data-anchor-id="check-testing-multiple-parameters">
<span class="header-section-number">6.5.1</span> Check: Testing Multiple Parameters</h3>
<p>In the following, we do inference about multiple parameters. We test <span class="math display">\[\begin{align*}
H_0:\;&amp;\beta_2=3\quad\text{and}\quad\beta_3=4\\
\text{versus}\quad H_1:\;&amp;\beta_2\neq 3\quad\text{and/or}\quad\beta_3\neq 4.
\end{align*}\]</span> Or equivalently <span class="math display">\[\begin{align*}
H_0:\;&amp;R\beta  = r^{(0)} \\
H_1:\;&amp;R\beta  \neq r^{(0)},
\end{align*}\]</span> where <span class="math display">\[
R=\left(
\begin{matrix}
0&amp;1&amp;0\\
0&amp;0&amp;1\\
\end{matrix}\right)\quad\text{ and }\quad
r^{(0)}=\left(\begin{matrix}3\\4\\\end{matrix}\right).
\]</span> The following <code>R</code> code can be used to test this hypothesis:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## Library containing the function 'linearHyothesis()' </span></span>
<span><span class="co">## for testing multiple parameters </span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/message.html">suppressMessages</a></span><span class="op">(</span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://r-forge.r-project.org/projects/car/">"car"</a></span><span class="op">)</span><span class="op">)</span> </span>
<span><span class="co">## See ?linearHypothesis</span></span>
<span></span>
<span><span class="co">## Generate one Monte Carlo sample (under H0)</span></span>
<span><span class="va">data</span>   <span class="op">&lt;-</span> <span class="fu">myDataGenerator</span><span class="op">(</span>n <span class="op">=</span> <span class="va">n</span>, beta <span class="op">=</span> <span class="va">beta_true</span><span class="op">)</span></span>
<span></span>
<span><span class="co">## Estimate the linear regression model parameters</span></span>
<span><span class="va">lm_obj</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">X_2</span> <span class="op">+</span> <span class="va">X_3</span>, data <span class="op">=</span> <span class="va">data</span><span class="op">)</span></span>
<span></span>
<span><span class="co">## Option 1:</span></span>
<span><span class="va">test_result</span> <span class="op">&lt;-</span> <span class="fu">car</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/car/man/linearHypothesis.html">linearHypothesis</a></span><span class="op">(</span></span>
<span>      model <span class="op">=</span> <span class="va">lm_obj</span>, </span>
<span>      hypothesis.matrix <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"X_2=3"</span>, <span class="st">"X_3=4"</span><span class="op">)</span><span class="op">)</span>   </span>
<span><span class="va">test_result</span>        </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear hypothesis test

Hypothesis:
X_2 = 3
X_3 = 4

Model 1: restricted model
Model 2: Y ~ X_2 + X_3

  Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
1      6 46.527                           
2      4 32.573  2    13.954 0.8568 0.4901</code></pre>
</div>
</div>
The <span class="math inline">\(p\)</span>-value
<center>
<span class="math inline">\(p_{\text{obs}}=\)</span> 0.4901 <span class="math inline">\(\;&gt;\alpha=0.05\)</span>
</center>
<p>is larger than the chosen significance level <span class="math inline">\(\alpha=0.05.\)</span> Thus we <strong>cannot reject</strong> the null hypothesis <span class="math display">\[
H_0:\;\beta_2=3\quad\text{and}\quad \beta_3=4.
\]</span></p>
<p>The following codes gives an alternative, equivalent way to compute the test result:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## Option 2:</span></span>
<span><span class="va">R</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">1</span>,<span class="fl">0</span><span class="op">)</span>,</span>
<span>           <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">0</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu">car</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/car/man/linearHypothesis.html">linearHypothesis</a></span><span class="op">(</span>model <span class="op">=</span> <span class="va">lm_obj</span>, </span>
<span>                      hypothesis.matrix <span class="op">=</span> <span class="va">R</span>, </span>
<span>                      rhs <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>,<span class="fl">4</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We simulated data under <span class="math inline">\(H_0\)</span> and thus it is not surprising that we cannot reject <span class="math inline">\(H_0.\)</span></p>
<p>However, in repeated samples we should nevertheless observe <span class="math inline">\(\alpha\cdot 100\%\)</span> type I errors (false rejections of <span class="math inline">\(H_0\)</span>) under <span class="math inline">\(H_0.\)</span> Let’s check the type-I-error rate using the following Monte Carlo simulation:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## Let's generate 5000 F-test decisions and check </span></span>
<span><span class="co">## whether the empirical rate of type I errors is </span></span>
<span><span class="co">## close to the theoretical significance level. </span></span>
<span><span class="va">B</span>               <span class="op">&lt;-</span> <span class="fl">5000</span> <span class="co"># MC replications</span></span>
<span><span class="va">F_test_pvalues</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="cn">NA</span>, times<span class="op">=</span><span class="va">B</span><span class="op">)</span></span>
<span><span class="co">##</span></span>
<span><span class="kw">for</span><span class="op">(</span><span class="va">r</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="va">B</span><span class="op">)</span><span class="op">{</span></span>
<span>  <span class="co">## generate new data (under H0)</span></span>
<span>  <span class="va">MC_data</span> <span class="op">&lt;-</span> <span class="fu">myDataGenerator</span><span class="op">(</span>n <span class="op">=</span> <span class="va">n</span>, beta <span class="op">=</span> <span class="va">beta_true</span><span class="op">)</span></span>
<span>  <span class="co">## estimate </span></span>
<span>  <span class="va">lm_obj</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">X_2</span> <span class="op">+</span> <span class="va">X_3</span>, data <span class="op">=</span> <span class="va">MC_data</span><span class="op">)</span></span>
<span>  <span class="co">## compute test and p-value</span></span>
<span>  <span class="va">p</span>       <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/car/man/linearHypothesis.html">linearHypothesis</a></span><span class="op">(</span><span class="va">lm_obj</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"X_2=3"</span>, <span class="st">"X_3=4"</span><span class="op">)</span><span class="op">)</span><span class="op">$</span><span class="va">`Pr(&gt;F)`</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span></span>
<span>  <span class="co">## save the p-value</span></span>
<span>  <span class="va">F_test_pvalues</span><span class="op">[</span><span class="va">r</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="va">p</span></span>
<span><span class="op">}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Using the collection of <span class="math inline">\(p\)</span>-value realizations (under <span class="math inline">\(H_0\)</span>) we can check whether the size equals the nominal size (significance level) <span class="math inline">\(\alpha.\)</span></p>
<p>For <span class="math inline">\(\alpha = 0.05:\)</span></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">alpha</span>        <span class="op">&lt;-</span>  <span class="fl">0.05</span>          <span class="co"># signif level</span></span>
<span><span class="va">rejections</span>   <span class="op">&lt;-</span> <span class="va">F_test_pvalues</span><span class="op">[</span><span class="va">F_test_pvalues</span> <span class="op">&lt;</span> <span class="va">alpha</span><span class="op">]</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">rejections</span><span class="op">)</span><span class="op">/</span><span class="va">B</span>, <span class="fl">4</span><span class="op">)</span> <span class="co"># actual type-I-error rate </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0524</code></pre>
</div>
</div>
<p>For <span class="math inline">\(\alpha = 0.01:\)</span></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">alpha</span>        <span class="op">&lt;-</span>  <span class="fl">0.01</span>  <span class="co"># signif level</span></span>
<span><span class="va">rejections</span>   <span class="op">&lt;-</span> <span class="va">F_test_pvalues</span><span class="op">[</span><span class="va">F_test_pvalues</span> <span class="op">&lt;</span> <span class="va">alpha</span><span class="op">]</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">rejections</span><span class="op">)</span><span class="op">/</span><span class="va">B</span>, <span class="fl">4</span><span class="op">)</span> <span class="co"># actual type-I-error rate </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0092</code></pre>
</div>
</div>
<p>Observations:</p>
<ol type="1">
<li>We correctly control for the type-I-error rate since the empirical type-I-error rate is not larger than the chosen significance level <span class="math inline">\(\alpha.\)</span>
</li>
<li>The <span class="math inline">\(F\)</span> test is not conservative since the empirical type-I-error rates essentially matches the chosen significance levels <span class="math inline">\(\alpha.\)</span>  In fact, if we would increase the number of Monte Carlo repetitions, the empirical type-I-error rate would converge to the nominal type-I-error rate <span class="math inline">\(\alpha\)</span> due to the law of large numbers.</li>
<li>Last but not least: All this works <strong>unconditionally</strong> on <span class="math inline">\(X\)</span> since the distribution of the <span class="math inline">\(F\)</span> statistic (<a href="#eq-Ftest" class="quarto-xref">Equation&nbsp;<span>6.3</span></a>) does not depend on <span class="math inline">\(X\)</span>.</li>
</ol>
<p>Next, we check how well the <span class="math inline">\(F\)</span> test detects certain <strong>violations of the null hypothesis</strong>. We do this by using the same data generating process, but by testing the following <span style="color:#FF0000">incorrect</span> null hypothesis: <span class="math display">\[\begin{align*}
H_0:\;&amp;{\color{red}\beta_2=4}\quad\text{and}\quad\beta_3=4\\
H_1:\;&amp;\beta_2\neq 4\quad\text{and/or}\quad\beta_3\neq 4
\end{align*}\]</span></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">B</span>               <span class="op">&lt;-</span> <span class="fl">5000</span> <span class="co"># MC replications</span></span>
<span><span class="va">F_test_pvalues</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="cn">NA</span>, times<span class="op">=</span><span class="va">B</span><span class="op">)</span></span>
<span><span class="co">##</span></span>
<span><span class="kw">for</span><span class="op">(</span><span class="va">r</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="va">B</span><span class="op">)</span><span class="op">{</span></span>
<span>  <span class="co">## generate new data </span></span>
<span>  <span class="va">MC_data</span> <span class="op">&lt;-</span> <span class="fu">myDataGenerator</span><span class="op">(</span>n    <span class="op">=</span> <span class="va">n</span>, beta <span class="op">=</span> <span class="va">beta_true</span><span class="op">)</span></span>
<span>  <span class="co">## estimate </span></span>
<span>  <span class="va">lm_obj</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">X_2</span> <span class="op">+</span> <span class="va">X_3</span>, data <span class="op">=</span> <span class="va">MC_data</span><span class="op">)</span></span>
<span>  <span class="co">## compute test and p-value (for a false H0)</span></span>
<span>  <span class="va">p</span>       <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/car/man/linearHypothesis.html">linearHypothesis</a></span><span class="op">(</span><span class="va">lm_obj</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"X_2=4"</span>, <span class="st">"X_3=4"</span><span class="op">)</span><span class="op">)</span><span class="op">$</span><span class="va">`Pr(&gt;F)`</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span></span>
<span>  <span class="co">## save the p-value</span></span>
<span>  <span class="va">F_test_pvalues</span><span class="op">[</span><span class="va">r</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="va">p</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="co">## Checking the power of the F test </span></span>
<span></span>
<span><span class="va">alpha</span>       <span class="op">&lt;-</span>  <span class="fl">0.05</span>  <span class="co"># signif_level</span></span>
<span><span class="va">rejections</span>  <span class="op">&lt;-</span> <span class="va">F_test_pvalues</span><span class="op">[</span><span class="va">F_test_pvalues</span> <span class="op">&lt;</span> <span class="va">alpha</span><span class="op">]</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">rejections</span><span class="op">)</span><span class="op">/</span><span class="va">B</span>  <span class="co"># power </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.204</code></pre>
</div>
</div>
<p>We can now correctly reject the false null hypothesis in approximately 20.4 % of all Monte Carlo replications.</p>
<p><strong>Caution:</strong> This means that we are not able to detect the violation of the null hypothesis in 79.6 % of cases. Therefore, we can never use an insignificant test result (<span class="math inline">\(p\)</span>-value <span class="math inline">\(\geq\alpha\)</span>) as a confirmation of the null hypothesis. Obviously, there are type-II-error events (not rejecting a false <span class="math inline">\(H_0\)</span>), but since we typically do not know the distribution of the test statistic under the alternative hypothesis, we cannot control the type-II-error rate. We can only control the type-I-error rate by using a small significance level <span class="math inline">\(\alpha\)</span>.</p>
<p>Moreover, note that the <span class="math inline">\(F\)</span> test is not informative about which part of the null hypothesis (<span class="math inline">\(\beta_2=4\)</span> and/or <span class="math inline">\(\beta_3=4\)</span>) is violated. We only get the information that at least one of the multiple parameter hypotheses is violated. Test statistics with this property are called <strong>omnibus tests</strong>.</p>
</section><section id="check-dualty-of-confidence-intervals-and-hypothesis-tests" class="level3" data-number="6.5.2"><h3 data-number="6.5.2" class="anchored" data-anchor-id="check-dualty-of-confidence-intervals-and-hypothesis-tests">
<span class="header-section-number">6.5.2</span> Check: Dualty of Confidence Intervals and Hypothesis Tests</h3>
<p>Confidence intervals can be computed using <code>R</code> as following:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## Significance level</span></span>
<span><span class="va">alpha</span>        <span class="op">&lt;-</span> <span class="fl">0.05</span></span>
<span><span class="co">## Confidence level</span></span>
<span><span class="va">conf_level</span>   <span class="op">&lt;-</span> <span class="fl">1</span> <span class="op">-</span> <span class="va">alpha</span></span>
<span></span>
<span><span class="co">## 95% CI for beta_2</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">lm_obj</span>, parm <span class="op">=</span> <span class="st">"X_2"</span>, level <span class="op">=</span> <span class="va">conf_level</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       2.5 %  97.5 %
X_2 2.984806 4.18956</code></pre>
</div>
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## 95% CI for beta_3 </span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">lm_obj</span>, parm <span class="op">=</span> <span class="st">"X_3"</span>, level <span class="op">=</span> <span class="va">conf_level</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       2.5 %   97.5 %
X_3 3.877389 4.489954</code></pre>
</div>
</div>
<p>We can use these two-sided confidence intervals to conduct hypotheses tests. This property of confidence intervals is called the <strong>duality of confidence intervals and hypothesis tests</strong>.</p>
<p>For instance, when testing the null hypothesis <span class="math display">\[\begin{align*}
H_0:&amp;\;\beta_2=3\\
\text{versus}\quad H_1: &amp;\;\beta_2\neq 3
\end{align*}\]</span> we can either use a <span class="math inline">\(t\)</span>-test or equivalently check whether the confidence interval <span class="math inline">\(\operatorname{CI}_{2,1-\alpha}\)</span> for <span class="math inline">\(\beta_2\)</span> contains the hypothetical value <span class="math inline">\(4\)</span> or not.</p>
<ul>
<li>In case of <span class="math inline">\(3    \in\operatorname{CI}_{2,1-\alpha}\)</span>, we cannot reject the null hypothesis <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\beta_2=3.\)</span>
</li>
<li>In case of <span class="math inline">\(3\not\in\operatorname{CI}_{2,1-\alpha}\)</span>, we can reject the null hypothesis <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\beta_2=3.\)</span>
</li>
</ul>
<p>If the Assumptions 1-4<span class="math inline">\(^\ast\)</span> hold true, then <span class="math inline">\(\operatorname{CI}_{2,1-\alpha}\)</span> is an exact confidence interval. That is, under the null hypothesis, it falsely rejects the null hypothesis in only <span class="math inline">\(\alpha\cdot 100\%\)</span> of resamplings. Let’s check this in the following Monte Carlo simulation:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## Significance level</span></span>
<span><span class="va">alpha</span>        <span class="op">&lt;-</span> <span class="fl">0.05</span></span>
<span></span>
<span><span class="co">## beta_2 safed separately</span></span>
<span><span class="va">beta_true_2</span>  <span class="op">&lt;-</span> <span class="va">beta_true</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span></span>
<span></span>
<span><span class="co">## Container to save all CI realizations</span></span>
<span><span class="va">confint_m</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="cn">NA</span>, nrow<span class="op">=</span><span class="fl">2</span>, ncol<span class="op">=</span><span class="va">B</span><span class="op">)</span></span>
<span><span class="co">##</span></span>
<span><span class="kw">for</span><span class="op">(</span><span class="va">r</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="va">B</span><span class="op">)</span><span class="op">{</span></span>
<span>  <span class="co">## generate new data </span></span>
<span>  <span class="va">MC_data</span> <span class="op">&lt;-</span> <span class="fu">myDataGenerator</span><span class="op">(</span>n <span class="op">=</span> <span class="va">n</span>, beta <span class="op">=</span> <span class="va">beta_true</span><span class="op">)</span></span>
<span>  <span class="co">## estimate</span></span>
<span>  <span class="va">lm_obj</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">X_2</span> <span class="op">+</span> <span class="va">X_3</span>, data <span class="op">=</span> <span class="va">MC_data</span><span class="op">)</span></span>
<span>  <span class="co">## compute confidence interval </span></span>
<span>  <span class="va">CI</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">lm_obj</span>, parm<span class="op">=</span><span class="st">"X_2"</span>, level <span class="op">=</span> <span class="fl">1</span> <span class="op">-</span> <span class="va">alpha</span><span class="op">)</span></span>
<span>  <span class="co">## save confidence interval</span></span>
<span>  <span class="va">confint_m</span><span class="op">[</span>,<span class="va">r</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="va">CI</span></span>
<span><span class="op">}</span></span>
<span><span class="co">## check whether true parameter is inside the CI</span></span>
<span><span class="va">inside_CI</span>  <span class="op">&lt;-</span> <span class="va">confint_m</span><span class="op">[</span><span class="fl">1</span>,<span class="op">]</span> <span class="op">&lt;=</span> <span class="va">beta_true_2</span> <span class="op">&amp;</span> </span>
<span>                <span class="va">beta_true_2</span> <span class="op">&lt;=</span> <span class="va">confint_m</span><span class="op">[</span><span class="fl">2</span>,<span class="op">]</span></span>
<span></span>
<span><span class="co">## CI-lower, CI-upper, beta_true_2 inside?</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span><span class="op">(</span><span class="va">confint_m</span><span class="op">)</span>, <span class="va">inside_CI</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       inside_CI
[1,] 2.507509 4.505450         1
[2,] 1.479413 4.468068         1
[3,] 2.540762 5.533256         1
[4,] 1.129250 6.473386         1
[5,] 1.167703 4.362476         1
[6,] 1.430087 4.107289         1</code></pre>
</div>
</div>
<p>The following code computes the relative frequency of confidence intervals <strong>not containing</strong> the true parameter value <span class="math inline">\((\beta_2=3)\)</span>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">inside_CI</span><span class="op">[</span><span class="va">inside_CI</span> <span class="op">==</span> <span class="cn">FALSE</span><span class="op">]</span><span class="op">)</span><span class="op">/</span><span class="va">B</span>, <span class="fl">4</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0442</code></pre>
</div>
</div>
<p>That’s good! The relative frequency is basically equal to the chosen <span class="math inline">\(\alpha=0.05\)</span> value.</p>
<p>Next, we visualize a subsample of <code>100</code> confidence intervals from the total sample of <code>5000</code> generated confidence interval realizations:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">nCIs</span> <span class="op">&lt;-</span> <span class="fl">100</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span>x<span class="op">=</span><span class="fl">0</span>, y<span class="op">=</span><span class="fl">0</span>,type<span class="op">=</span><span class="st">"n"</span>, xlim<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="va">nCIs</span><span class="op">)</span>, ylim<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/range.html">range</a></span><span class="op">(</span><span class="va">confint_m</span><span class="op">[</span>,<span class="fl">1</span><span class="op">:</span><span class="va">nCIs</span><span class="op">]</span><span class="op">)</span>,</span>
<span>     ylab<span class="op">=</span><span class="st">""</span>, xlab<span class="op">=</span><span class="st">"Resamplings"</span>, main<span class="op">=</span><span class="st">"Confidence Intervals"</span><span class="op">)</span></span>
<span><span class="kw">for</span><span class="op">(</span><span class="va">r</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="va">nCIs</span><span class="op">)</span><span class="op">{</span></span>
<span>  <span class="kw">if</span><span class="op">(</span><span class="va">inside_CI</span><span class="op">[</span><span class="va">r</span><span class="op">]</span><span class="op">==</span><span class="cn">TRUE</span><span class="op">)</span><span class="op">{</span></span>
<span>      <span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span><span class="op">(</span>x<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">r</span>,<span class="va">r</span><span class="op">)</span>, y<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">confint_m</span><span class="op">[</span><span class="fl">1</span>,<span class="va">r</span><span class="op">]</span>, <span class="va">confint_m</span><span class="op">[</span><span class="fl">2</span>,<span class="va">r</span><span class="op">]</span><span class="op">)</span>, lwd<span class="op">=</span><span class="fl">2</span>, col<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/grDevices/gray.html">gray</a></span><span class="op">(</span><span class="fl">.5</span>,<span class="fl">.5</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="op">}</span><span class="kw">else</span><span class="op">{</span></span>
<span>      <span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span><span class="op">(</span>x<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">r</span>,<span class="va">r</span><span class="op">)</span>, y<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">confint_m</span><span class="op">[</span><span class="fl">1</span>,<span class="va">r</span><span class="op">]</span>, <span class="va">confint_m</span><span class="op">[</span><span class="fl">2</span>,<span class="va">r</span><span class="op">]</span><span class="op">)</span>, lwd<span class="op">=</span><span class="fl">2</span>, col<span class="op">=</span><span class="st">"darkred"</span><span class="op">)</span></span>
<span>    <span class="op">}</span></span>
<span><span class="op">}</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/axis.html">axis</a></span><span class="op">(</span><span class="fl">4</span>, at<span class="op">=</span><span class="va">beta_true_2</span>, labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/expression.html">expression</a></span><span class="op">(</span><span class="va">beta</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/abline.html">abline</a></span><span class="op">(</span>h<span class="op">=</span><span class="va">beta_true_2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="06-Small-Sample-Inference_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>As expected, only about <span class="math inline">\(\alpha\cdot 100\%=5\%\)</span> of all confidence intervals do not contain the true parameter value <span class="math inline">\(\beta_2=3\)</span>, but about <span class="math inline">\((1-\alpha)\cdot 100\%=95\%\)</span> of all confidence intervals contain the true parameter value <span class="math inline">\(\beta_2=3\)</span>.</p>
</section></section><section id="sec-RDSSInf" class="level2" data-number="6.6"><h2 data-number="6.6" class="anchored" data-anchor-id="sec-RDSSInf">
<span class="header-section-number">6.6</span> Real Data Example</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## The AER package contains a lot of datasets </span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/message.html">suppressPackageStartupMessages</a></span><span class="op">(</span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">AER</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co">## Attach the DoctorVisits data to make it usable</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="st">"DoctorVisits"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">lm_obj</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">visits</span> <span class="op">~</span> <span class="va">gender</span> <span class="op">+</span> <span class="va">age</span> <span class="op">+</span> <span class="va">income</span>, data <span class="op">=</span> <span class="va">DoctorVisits</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The above <code>R</code> codes estimate the following regression model <span class="math display">\[
Y_i = \beta_1 + \beta_{gender} X_{gender,i}
              + \beta_{age} X_{age,i}
              + \beta_{income} X_{income,i} + \varepsilon_i,
\]</span> where <span class="math inline">\(i=1,\dots,n\)</span> and</p>
<ul>
<li>
<span class="math inline">\(X_{gender,i}=1\)</span> if the <span class="math inline">\(i\)</span>th subject is a woman and <span class="math inline">\(X_{gender,i}=0\)</span> if the <span class="math inline">\(i\)</span>th subject is a man</li>
<li>
<span class="math inline">\(X_{age,i}\)</span> is the age of subject <span class="math inline">\(i\)</span> measured in years divided by <span class="math inline">\(100\)</span>
</li>
<li>
<span class="math inline">\(X_{income,i}\)</span> is the annual income of subject <span class="math inline">\(i\)</span> in tens of thousands of dollars</li>
</ul>
<p>The following <code>R</code> codes produces the classic regression output table (simular tables are produced by all statistical/econometric software packages):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lm_obj_summary</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">lm_obj</span><span class="op">)</span></span>
<span><span class="va">lm_obj_summary</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = visits ~ gender + age + income, data = DoctorVisits)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.5009 -0.3435 -0.2306 -0.1682  8.6174 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   0.15371    0.03607   4.262 2.07e-05 ***
genderfemale  0.06245    0.02345   2.662  0.00778 ** 
age           0.40235    0.05713   7.043 2.13e-12 ***
income       -0.08231    0.03167  -2.599  0.00938 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7908 on 5186 degrees of freedom
Multiple R-squared:  0.01885,   Adjusted R-squared:  0.01829 
F-statistic: 33.22 on 3 and 5186 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The above regression output table contains the following information:</p>
<ul>
<li><p><strong>Estimate:</strong> The column “Estimate” containes the estimates <span class="math display">\[
\hat\beta_{j},\quad j\in\{1,gender, age, income\}
\]</span> You can extract them using <code>coef(lm_obj)</code>.</p></li>
<li>
<p><strong>Std. Error:</strong> The column “Std. Error” containes the estimates <span class="math display">\[
\widehat{\operatorname{SE}}(\hat\beta_{j}|X),\quad j\in\{1,gender, age, income\}
\]</span></p>
<ul>
<li>You can extract the total <span class="math inline">\((K\times K)=(4\times 4)\)</span> variance-covariance matrix estimate <span class="math inline">\(\widehat{Var}(\hat\beta|X)\)</span> using <code>vcov(lm_obj)</code>.</li>
<li>The diagonal <code>diag(vcov(lm_obj))</code> contains the variance estimates <span class="math inline">\(\widehat{Var}(\hat\beta_j|X)\)</span>, <span class="math inline">\(j\in\{1,gender, age, income\}\)</span>.</li>
<li>The square root of the diagonal <code>sqrt(diag(vcov(lm_obj)))</code> allows you to compute the estimated standard errors shown in the regression table.</li>
</ul>
</li>
<li><p><strong>t value:</strong> The column “t value” contains the observed <span class="math inline">\(t\)</span> test statistics <span class="math display">\[
T_{obs,j}=\frac{\hat\beta_{j}-0}{\widehat{\operatorname{SE}}(\hat\beta_{j}|X)},\quad j\in\{1,gender, age, income\}
\]</span> You can extract the values using <code>lm_obj_summary$coefficients[,3]</code>.</p></li>
<li><p><strong>Pr(&gt;|t|):</strong> The column “Pr(&gt;|t|)” contains the <span class="math inline">\(p\)</span> values <span class="math display">\[
P_{H_0}(|t|&gt;t_{obs,j}),\quad j\in\{1,gender, age, income\}
\]</span> You can extract the values using <code>lm_obj_summary$coefficients[,4]</code>.</p></li>
<li><p><strong>Residual standard error</strong> <span class="math inline">\(\sqrt{\frac{1}{n-K}\sum_{i=1}^n\hat\varepsilon^2_i}=\)</span> <code>sqrt(sum(resid(lm_obj)^2)/(n-4))</code> <span class="math inline">\(=\)</span> 0.7908</p></li>
<li><p><strong>Multiple R-squared:</strong> <span class="math inline">\(R^2=\)</span> <code>lm_obj_summary$r.squared</code> <span class="math inline">\(=\)</span> 0.01885</p></li>
<li><p><strong>Adjusted R-squared:</strong> <span class="math inline">\(\bar{R}^2=\)</span> <code>lm_obj_summary$adj.r.squared</code> <span class="math inline">\(=\)</span> 0.01829</p></li>
<li><p><strong>F-statistic:</strong> This is a standard <span class="math inline">\(F\)</span> test that tests the null hypothesis that all parameters except the intercept are zero; i.e.<br><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\beta_{gender}=\beta_{age}=\beta_{income}=0\)</span><br> versus<br><span class="math inline">\(H_1\)</span>: At least one parameter is not zero. <code>R</code>’s <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> functions reports an observed <span class="math inline">\(F\)</span> statistic value of <span class="math inline">\(33.22\)</span> which needs to be evaluated for an <span class="math inline">\(F\)</span> distribution with <span class="math inline">\(3\)</span> and <span class="math inline">\(5186\)</span> degrees of freedom leading to a <span class="math inline">\(p\)</span>-value <span class="math inline">\(p&lt; 0.00001.\)</span> <br><br> You can replicate this <span class="math inline">\(F\)</span>-test result using the following <code>R</code> code:</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">car</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/car/man/linearHypothesis.html">linearHypothesis</a></span><span class="op">(</span></span>
<span>      model <span class="op">=</span> <span class="va">lm_obj</span>, </span>
<span>      hypothesis.matrix <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"genderfemale=0"</span>, <span class="st">"age=0"</span>, <span class="st">"income=0"</span><span class="op">)</span><span class="op">)</span>  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear hypothesis test

Hypothesis:
genderfemale = 0
age = 0
income = 0

Model 1: restricted model
Model 2: visits ~ gender + age + income

  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1   5189 3305.5                                  
2   5186 3243.2  3     62.32 33.218 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<!-- #### Interpretation of $\hat\beta_{gender}$ {-} -->
<!-- Since $X_{gender,i}$ is a dummy variable,  -->
<section id="r-package-stargazer" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="r-package-stargazer">
<code>R</code> Package Stargazer</h4>
<p>Beautiful and “publication ready” regression outputs can be produced using the <code>R</code> package <code>stargazer</code> and its function <code>stargazer()</code>:</p>
<center>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## Hint: use type = "latex" </span></span>
<span><span class="co">## to produce a latex table</span></span>
<span><span class="fu">stargazer</span><span class="op">(</span><span class="va">lm_obj</span>, type<span class="op">=</span><span class="st">"html"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<table style="text-align:center">
<tbody><tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
<em>Dependent variable:</em>
</td>
</tr>
<tr>
<td>
</td>
<td colspan="1" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
visits
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
genderfemale
</td>
<td>
0.062<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.023)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
age
</td>
<td>
0.402<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.057)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
income
</td>
<td>
-0.082<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.032)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
0.154<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.036)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
5,190
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td>
0.019
</td>
</tr>
<tr>
<td style="text-align:left">
Adjusted R<sup>2</sup>
</td>
<td>
0.018
</td>
</tr>
<tr>
<td style="text-align:left">
Residual Std. Error
</td>
<td>
0.791 (df = 5186)
</td>
</tr>
<tr>
<td style="text-align:left">
F Statistic
</td>
<td>
33.218<sup>***</sup> (df = 3; 5186)
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td style="text-align:right">
<sup><em></em></sup>p&lt;0.1; <sup><strong></strong></sup>p&lt;0.05; <sup></sup>p&lt;0.01
</td>
</tr>
</tbody></table>
</div>
</center>
</section><section id="critical-discussion-of-the-regression-above-results" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="critical-discussion-of-the-regression-above-results">Critical Discussion of the Regression above Results</h4>
<p>The above real data analysis does <strong>not</strong> fit into the small sample inference framework we introduced in this chapter.</p>
<ol type="1">
<li>The dependent variable <span class="math inline">\(Y_i\)</span> <code>visits</code> is a <em>categorial</em> variable taking finitely many discrete values, indeed
<center>
<code>unique(DoctorVisits$visits)</code> = 1, 2, 3, 4, 8, 5, 7, 6, 9, 0.
</center>
Consequently, the error term <span class="math inline">\(\varepsilon_i\)</span> <strong>cannot be normal distributed</strong>.</li>
<li>The diagnostic plot (“Residuals versus Fitted”) indicates a possible issue <strong>violation of the homoskedasticity assumption</strong>. In case of homokedastic variances, the data points <span class="math inline">\((\hat\varepsilon_i,\hat{Y}_i)\)</span>, <span class="math inline">\(i=1,\dots,n\)</span> should roughly show a homogenous scattering across the fitted values <span class="math inline">\(\hat{Y}_i=X\hat\beta\)</span>. This seems not to be the case here.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## Diagonstic Plot </span></span>
<span><span class="co">## Residuals versus fitted values</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">lm_obj</span>, which <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="06-Small-Sample-Inference_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Lukily, the data set <code>DoctorVisits</code> actually has a <strong>large sample size</strong> of <span class="math inline">\(n=\)</span> 5190 and thus there is a way out of this problem: The large sample inference framework introduced in the next chapter.</p>
</section></section><section id="exercises" class="level2" data-number="6.7"><h2 data-number="6.7" class="anchored" data-anchor-id="exercises">
<span class="header-section-number">6.7</span> Exercises</h2>
<!-- * [Exercises for Chapter 6](https://www.dropbox.com/scl/fi/g6hiwoprjewwsbr09t217/Ch5_Exercises1.pdf?rlkey=s6642zm8ufj173mhmbtoj0wvf&dl=0)


* [Exercises of Chapter 6 with Solutions](https://www.dropbox.com/scl/fi/codmlxtkr9p4wugd7knm0/Ch5_Exercises_with_Solutions1.pdf?rlkey=4s4g3nu4k2ycvlg4cm2n5xcat&dl=0)

-->
</section><section id="references" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="references">References</h2>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Altman_Bland_1995" class="csl-entry" role="listitem">
Altman, Douglas G, and J Martin Bland. 1995. <span>“Statistics Notes: Absence of Evidence Is Not Evidence of Absence.”</span> <em>British Medical Journal</em> 311 (7003): 485.
</div>
<div id="ref-Hayashi2000" class="csl-entry" role="listitem">
Hayashi, Fumio. 2000. <em>Econometrics</em>. Princeton University Press.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./05-Multiple-Linear-Regression.html" class="pagination-link" aria-label="Multiple Linear Regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Multiple Linear Regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./07-Asymptotics.html" class="pagination-link" aria-label="Large Sample Inference">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Large Sample Inference</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>