<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>8.1 The IV Estimator with a Single Regressor and a Single Instrument | Econometrics (M.Sc.)</title>
  <meta name="description" content="8.1 The IV Estimator with a Single Regressor and a Single Instrument | Econometrics (M.Sc.)" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="8.1 The IV Estimator with a Single Regressor and a Single Instrument | Econometrics (M.Sc.)" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="/images/mylogo.png" />
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="8.1 The IV Estimator with a Single Regressor and a Single Instrument | Econometrics (M.Sc.)" />
  
  
  <meta name="twitter:image" content="/images/mylogo.png" />

<meta name="author" content="Prof. Dr. Dominik Liebl" />


<meta name="date" content="2021-10-11" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="8-ivr.html"/>
<link rel="next" href="8.2-TGIVRM.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
<link rel="stylesheet" href="toc.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="organization-of-the-course.html"><a href="organization-of-the-course.html"><i class="fa fa-check"></i>Organization of the Course</a></li>
<li class="chapter" data-level="" data-path="literature.html"><a href="literature.html"><i class="fa fa-check"></i>Literature</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="1-introduction-to-r.html"><a href="1-introduction-to-r.html"><i class="fa fa-check"></i><b>1</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="1.1-short-glossary.html"><a href="1.1-short-glossary.html"><i class="fa fa-check"></i><b>1.1</b> Short Glossary</a></li>
<li class="chapter" data-level="1.2" data-path="1.2-first-steps.html"><a href="1.2-first-steps.html"><i class="fa fa-check"></i><b>1.2</b> First Steps</a></li>
<li class="chapter" data-level="1.3" data-path="1.3-further-data-objects.html"><a href="1.3-further-data-objects.html"><i class="fa fa-check"></i><b>1.3</b> Further Data Objects</a></li>
<li class="chapter" data-level="1.4" data-path="1.4-simple-regression-analysis-using-r.html"><a href="1.4-simple-regression-analysis-using-r.html"><i class="fa fa-check"></i><b>1.4</b> Simple Regression Analysis using R</a></li>
<li class="chapter" data-level="1.5" data-path="1.5-programming-in-r.html"><a href="1.5-programming-in-r.html"><i class="fa fa-check"></i><b>1.5</b> Programming in R</a></li>
<li class="chapter" data-level="1.6" data-path="1.6-r-packages.html"><a href="1.6-r-packages.html"><i class="fa fa-check"></i><b>1.6</b> R-packages</a></li>
<li class="chapter" data-level="1.7" data-path="1.7-tidyverse.html"><a href="1.7-tidyverse.html"><i class="fa fa-check"></i><b>1.7</b> Tidyverse</a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="1.7-tidyverse.html"><a href="1.7-tidyverse.html#tidyverse-plotting-basics"><i class="fa fa-check"></i><b>1.7.1</b> Tidyverse: Plotting Basics</a></li>
<li class="chapter" data-level="1.7.2" data-path="1.7-tidyverse.html"><a href="1.7-tidyverse.html#tidyverse-data-wrangling-basics"><i class="fa fa-check"></i><b>1.7.2</b> Tidyverse: Data Wrangling Basics</a></li>
<li class="chapter" data-level="1.7.3" data-path="1.7-tidyverse.html"><a href="1.7-tidyverse.html#the-pipe-operator"><i class="fa fa-check"></i><b>1.7.3</b> The pipe operator <code>%&gt;%</code></a></li>
<li class="chapter" data-level="1.7.4" data-path="1.7-tidyverse.html"><a href="1.7-tidyverse.html#the-group_by-function"><i class="fa fa-check"></i><b>1.7.4</b> The <code>group_by()</code> function</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="1.8-further-links.html"><a href="1.8-further-links.html"><i class="fa fa-check"></i><b>1.8</b> Further Links</a>
<ul>
<li class="chapter" data-level="1.8.1" data-path="1.8-further-links.html"><a href="1.8-further-links.html#further-r-intros"><i class="fa fa-check"></i><b>1.8.1</b> Further R-Intros</a></li>
<li class="chapter" data-level="1.8.2" data-path="1.8-further-links.html"><a href="1.8-further-links.html#version-control-gitgithub"><i class="fa fa-check"></i><b>1.8.2</b> Version Control (Git/GitHub)</a></li>
<li class="chapter" data-level="1.8.3" data-path="1.8-further-links.html"><a href="1.8-further-links.html#r-ladies"><i class="fa fa-check"></i><b>1.8.3</b> R-Ladies</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="2-review-probability-and-statistics.html"><a href="2-review-probability-and-statistics.html"><i class="fa fa-check"></i><b>2</b> Review: Probability and Statistics</a>
<ul>
<li class="chapter" data-level="2.1" data-path="2.1-probability-theory.html"><a href="2.1-probability-theory.html"><i class="fa fa-check"></i><b>2.1</b> Probability Theory</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="2.1-probability-theory.html"><a href="2.1-probability-theory.html#sample-spaces-and-events"><i class="fa fa-check"></i><b>2.1.1</b> Sample Spaces and Events</a></li>
<li class="chapter" data-level="2.1.2" data-path="2.1-probability-theory.html"><a href="2.1-probability-theory.html#probability"><i class="fa fa-check"></i><b>2.1.2</b> Probability</a></li>
<li class="chapter" data-level="2.1.3" data-path="2.1-probability-theory.html"><a href="2.1-probability-theory.html#independent-events"><i class="fa fa-check"></i><b>2.1.3</b> Independent Events</a></li>
<li class="chapter" data-level="2.1.4" data-path="2.1-probability-theory.html"><a href="2.1-probability-theory.html#conditional-probability"><i class="fa fa-check"></i><b>2.1.4</b> Conditional Probability</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="2.2-random-variables.html"><a href="2.2-random-variables.html"><i class="fa fa-check"></i><b>2.2</b> Random Variables</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="2.2-random-variables.html"><a href="2.2-random-variables.html#univariate-distribution-and-probability-functions"><i class="fa fa-check"></i><b>2.2.1</b> Univariate Distribution and Probability Functions</a></li>
<li class="chapter" data-level="2.2.2" data-path="2.2-random-variables.html"><a href="2.2-random-variables.html#multivariate-distribution-and-probability-functions"><i class="fa fa-check"></i><b>2.2.2</b> Multivariate Distribution and Probability Functions</a></li>
<li class="chapter" data-level="2.2.3" data-path="2.2-random-variables.html"><a href="2.2-random-variables.html#means-and-moments"><i class="fa fa-check"></i><b>2.2.3</b> Means and Moments</a></li>
<li class="chapter" data-level="2.2.4" data-path="2.2-random-variables.html"><a href="2.2-random-variables.html#unconditional-means"><i class="fa fa-check"></i><b>2.2.4</b> Unconditional Means</a></li>
<li class="chapter" data-level="2.2.5" data-path="2.2-random-variables.html"><a href="2.2-random-variables.html#conditional-means"><i class="fa fa-check"></i><b>2.2.5</b> Conditional Means</a></li>
<li class="chapter" data-level="2.2.6" data-path="2.2-random-variables.html"><a href="2.2-random-variables.html#means-of-transformed-random-variables-and-moments"><i class="fa fa-check"></i><b>2.2.6</b> Means of Transformed Random Variables and Moments</a></li>
<li class="chapter" data-level="2.2.7" data-path="2.2-random-variables.html"><a href="2.2-random-variables.html#independent-random-variables"><i class="fa fa-check"></i><b>2.2.7</b> Independent Random Variables</a></li>
<li class="chapter" data-level="2.2.8" data-path="2.2-random-variables.html"><a href="2.2-random-variables.html#i.i.d.-samples"><i class="fa fa-check"></i><b>2.2.8</b> I.I.D. Samples</a></li>
<li class="chapter" data-level="2.2.9" data-path="2.2-random-variables.html"><a href="2.2-random-variables.html#some-important-discrete-random-variables"><i class="fa fa-check"></i><b>2.2.9</b> Some Important Discrete Random Variables</a></li>
<li class="chapter" data-level="2.2.10" data-path="2.2-random-variables.html"><a href="2.2-random-variables.html#some-important-continuous-random-variables"><i class="fa fa-check"></i><b>2.2.10</b> Some Important Continuous Random Variables</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="3-ch:SLR.html"><a href="3-ch:SLR.html"><i class="fa fa-check"></i><b>3</b> Review: Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="3.1" data-path="3.1-the-simple-linear-regression-model.html"><a href="3.1-the-simple-linear-regression-model.html"><i class="fa fa-check"></i><b>3.1</b> The Simple Linear Regression Model</a>
<ul>
<li class="chapter" data-level="" data-path="3.1-the-simple-linear-regression-model.html"><a href="3.1-the-simple-linear-regression-model.html#the-data-generating-process"><i class="fa fa-check"></i>The Data-Generating Process</a></li>
<li class="chapter" data-level="3.1.1" data-path="3.1-the-simple-linear-regression-model.html"><a href="3.1-the-simple-linear-regression-model.html#assumptions-about-the-error-term"><i class="fa fa-check"></i><b>3.1.1</b> Assumptions About the Error Term</a></li>
<li class="chapter" data-level="3.1.2" data-path="3.1-the-simple-linear-regression-model.html"><a href="3.1-the-simple-linear-regression-model.html#the-population-regression-line"><i class="fa fa-check"></i><b>3.1.2</b> The Population Regression Line</a></li>
<li class="chapter" data-level="3.1.3" data-path="3.1-the-simple-linear-regression-model.html"><a href="3.1-the-simple-linear-regression-model.html#terminology-estimates-versus-estimators"><i class="fa fa-check"></i><b>3.1.3</b> Terminology: Estimates versus Estimators</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="3.2-ordinary-least-squares-estimation.html"><a href="3.2-ordinary-least-squares-estimation.html"><i class="fa fa-check"></i><b>3.2</b> Ordinary Least Squares Estimation</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="3.2-ordinary-least-squares-estimation.html"><a href="3.2-ordinary-least-squares-estimation.html#terminology-sample-regression-line-prediction-and-residuals"><i class="fa fa-check"></i><b>3.2.1</b> Terminology: Sample Regression Line, Prediction and Residuals</a></li>
<li class="chapter" data-level="3.2.2" data-path="3.2-ordinary-least-squares-estimation.html"><a href="3.2-ordinary-least-squares-estimation.html#sec:SLROLS"><i class="fa fa-check"></i><b>3.2.2</b> Deriving the Expression of the OLS Estimator</a></li>
<li class="chapter" data-level="3.2.3" data-path="3.2-ordinary-least-squares-estimation.html"><a href="3.2-ordinary-least-squares-estimation.html#behavior-of-the-ols-estimates-for-resampled-data-conditionally-on-x_i"><i class="fa fa-check"></i><b>3.2.3</b> Behavior of the OLS Estimates for Resampled Data (conditionally on <span class="math inline">\(X_i\)</span>)</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="3.3-properties-of-the-ols-estimator.html"><a href="3.3-properties-of-the-ols-estimator.html"><i class="fa fa-check"></i><b>3.3</b> Properties of the OLS Estimator</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="3.3-properties-of-the-ols-estimator.html"><a href="3.3-properties-of-the-ols-estimator.html#mean-and-bias-of-the-ols-estimator"><i class="fa fa-check"></i><b>3.3.1</b> Mean and Bias of the OLS Estimator</a></li>
<li class="chapter" data-level="3.3.2" data-path="3.3-properties-of-the-ols-estimator.html"><a href="3.3-properties-of-the-ols-estimator.html#variance-of-the-ols-estimator"><i class="fa fa-check"></i><b>3.3.2</b> Variance of the OLS Estimator</a></li>
<li class="chapter" data-level="3.3.3" data-path="3.3-properties-of-the-ols-estimator.html"><a href="3.3-properties-of-the-ols-estimator.html#consistency-of-the-ols-estimator"><i class="fa fa-check"></i><b>3.3.3</b> Consistency of the OLS Estimator</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="4-ch:MLR.html"><a href="4-ch:MLR.html"><i class="fa fa-check"></i><b>4</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="4.1" data-path="4.1-assumptions.html"><a href="4.1-assumptions.html"><i class="fa fa-check"></i><b>4.1</b> Assumptions</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="4.1-assumptions.html"><a href="4.1-assumptions.html#some-implications-of-the-exogeneity-assumption"><i class="fa fa-check"></i><b>4.1.1</b> Some Implications of the Exogeneity Assumption</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="4.2-deriving-the-expression-of-the-ols-estimator.html"><a href="4.2-deriving-the-expression-of-the-ols-estimator.html"><i class="fa fa-check"></i><b>4.2</b> Deriving the Expression of the OLS Estimator</a></li>
<li class="chapter" data-level="4.3" data-path="4.3-some-quantities-of-interest.html"><a href="4.3-some-quantities-of-interest.html"><i class="fa fa-check"></i><b>4.3</b> Some Quantities of Interest</a></li>
<li class="chapter" data-level="4.4" data-path="4.4-method-of-moments-estimator.html"><a href="4.4-method-of-moments-estimator.html"><i class="fa fa-check"></i><b>4.4</b> Method of Moments Estimator</a></li>
<li class="chapter" data-level="4.5" data-path="4.5-unbiasedness-of-hatbetax.html"><a href="4.5-unbiasedness-of-hatbetax.html"><i class="fa fa-check"></i><b>4.5</b> Unbiasedness of <span class="math inline">\(\hat\beta|X\)</span></a></li>
<li class="chapter" data-level="4.6" data-path="4.6-ch:VarEstBeta.html"><a href="4.6-ch:VarEstBeta.html"><i class="fa fa-check"></i><b>4.6</b> Variance of <span class="math inline">\(\hat\beta|X\)</span></a></li>
<li class="chapter" data-level="4.7" data-path="4.7-the-gauss-markov-theorem.html"><a href="4.7-the-gauss-markov-theorem.html"><i class="fa fa-check"></i><b>4.7</b> The Gauss-Markov Theorem</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="5-ch:SSINF.html"><a href="5-ch:SSINF.html"><i class="fa fa-check"></i><b>5</b> Small Sample Inference</a>
<ul>
<li class="chapter" data-level="5.1" data-path="5.1-ch:testmultp.html"><a href="5.1-ch:testmultp.html"><i class="fa fa-check"></i><b>5.1</b> Hypothesis Tests about Multiple Parameters</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="5.1-ch:testmultp.html"><a href="5.1-ch:testmultp.html#the-test-statistic-and-its-null-distribution"><i class="fa fa-check"></i><b>5.1.1</b> The Test Statistic and its Null Distribution</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="5.2-ch:testingsinglep.html"><a href="5.2-ch:testingsinglep.html"><i class="fa fa-check"></i><b>5.2</b> Tests about One Parameter</a></li>
<li class="chapter" data-level="5.3" data-path="5.3-testtheory.html"><a href="5.3-testtheory.html"><i class="fa fa-check"></i><b>5.3</b> Testtheory</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="5.3-testtheory.html"><a href="5.3-testtheory.html#significance-level"><i class="fa fa-check"></i><b>5.3.1</b> Significance Level</a></li>
<li class="chapter" data-level="5.3.2" data-path="5.3-testtheory.html"><a href="5.3-testtheory.html#critical-value-for-the-f-test"><i class="fa fa-check"></i><b>5.3.2</b> Critical Value for the <span class="math inline">\(F\)</span>-Test</a></li>
<li class="chapter" data-level="5.3.3" data-path="5.3-testtheory.html"><a href="5.3-testtheory.html#critical-values-for-the-t-test"><i class="fa fa-check"></i><b>5.3.3</b> Critical Value(s) for the <span class="math inline">\(t\)</span>-Test</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="5.4-type-ii-error-and-power.html"><a href="5.4-type-ii-error-and-power.html"><i class="fa fa-check"></i><b>5.4</b> Type II Error and Power</a></li>
<li class="chapter" data-level="5.5" data-path="5.5-p-value.html"><a href="5.5-p-value.html"><i class="fa fa-check"></i><b>5.5</b> <span class="math inline">\(p\)</span>-Value</a></li>
<li class="chapter" data-level="5.6" data-path="5.6-CIsmallsample.html"><a href="5.6-CIsmallsample.html"><i class="fa fa-check"></i><b>5.6</b> Confidence Intervals</a></li>
<li class="chapter" data-level="5.7" data-path="5.7-PSSI.html"><a href="5.7-PSSI.html"><i class="fa fa-check"></i><b>5.7</b> Practice: Small Sample Inference</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="5.7-PSSI.html"><a href="5.7-PSSI.html#normally-distributed-hatbetax"><i class="fa fa-check"></i><b>5.7.1</b> Normally Distributed <span class="math inline">\(\hat\beta|X\)</span></a></li>
<li class="chapter" data-level="5.7.2" data-path="5.7-PSSI.html"><a href="5.7-PSSI.html#testing-multiple-parameters"><i class="fa fa-check"></i><b>5.7.2</b> Testing Multiple Parameters</a></li>
<li class="chapter" data-level="5.7.3" data-path="5.7-PSSI.html"><a href="5.7-PSSI.html#dualty-of-confidence-intervals-and-hypothesis-tests"><i class="fa fa-check"></i><b>5.7.3</b> Dualty of Confidence Intervals and Hypothesis Tests</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="6-ch:LSINF.html"><a href="6-ch:LSINF.html"><i class="fa fa-check"></i><b>6</b> Large Sample Inference</a>
<ul>
<li class="chapter" data-level="6.1" data-path="6.1-tools-for-asymptotic-statistics.html"><a href="6.1-tools-for-asymptotic-statistics.html"><i class="fa fa-check"></i><b>6.1</b> Tools for Asymptotic Statistics</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="6.1-tools-for-asymptotic-statistics.html"><a href="6.1-tools-for-asymptotic-statistics.html#modes-of-convergence"><i class="fa fa-check"></i><b>6.1.1</b> Modes of Convergence</a></li>
<li class="chapter" data-level="" data-path="6.1-tools-for-asymptotic-statistics.html"><a href="6.1-tools-for-asymptotic-statistics.html#four-important-modes-of-convergence"><i class="fa fa-check"></i>Four Important Modes of Convergence</a></li>
<li class="chapter" data-level="" data-path="6.1-tools-for-asymptotic-statistics.html"><a href="6.1-tools-for-asymptotic-statistics.html#relations-among-modes-of-convergence"><i class="fa fa-check"></i>Relations among Modes of Convergence</a></li>
<li class="chapter" data-level="6.1.2" data-path="6.1-tools-for-asymptotic-statistics.html"><a href="6.1-tools-for-asymptotic-statistics.html#continuous-mapping-theorem-cmt"><i class="fa fa-check"></i><b>6.1.2</b> Continuous Mapping Theorem (CMT)</a></li>
<li class="chapter" data-level="6.1.3" data-path="6.1-tools-for-asymptotic-statistics.html"><a href="6.1-tools-for-asymptotic-statistics.html#slutsky-theorem"><i class="fa fa-check"></i><b>6.1.3</b> Slutsky Theorem</a></li>
<li class="chapter" data-level="6.1.4" data-path="6.1-tools-for-asymptotic-statistics.html"><a href="6.1-tools-for-asymptotic-statistics.html#law-of-large-numbers-lln-and-central-limit-theorem-clt"><i class="fa fa-check"></i><b>6.1.4</b> Law of Large Numbers (LLN) and Central Limit Theorem (CLT)</a></li>
<li class="chapter" data-level="6.1.5" data-path="6.1-tools-for-asymptotic-statistics.html"><a href="6.1-tools-for-asymptotic-statistics.html#estimators-as-a-sequences-of-random-variables"><i class="fa fa-check"></i><b>6.1.5</b> Estimators as a Sequences of Random Variables</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="6.2-asymptotics-under-the-classic-regression-model.html"><a href="6.2-asymptotics-under-the-classic-regression-model.html"><i class="fa fa-check"></i><b>6.2</b> Asymptotics under the Classic Regression Model</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="6.2-asymptotics-under-the-classic-regression-model.html"><a href="6.2-asymptotics-under-the-classic-regression-model.html#the-case-of-heteroscedasticity"><i class="fa fa-check"></i><b>6.2.1</b> The Case of Heteroscedasticity</a></li>
<li class="chapter" data-level="6.2.2" data-path="6.2-asymptotics-under-the-classic-regression-model.html"><a href="6.2-asymptotics-under-the-classic-regression-model.html#hypothesis-testing-and-confidence-intervals"><i class="fa fa-check"></i><b>6.2.2</b> Hypothesis Testing and Confidence Intervals</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="6.3-robust-confidence-intervals.html"><a href="6.3-robust-confidence-intervals.html"><i class="fa fa-check"></i><b>6.3</b> Robust Confidence Intervals</a></li>
<li class="chapter" data-level="6.4" data-path="6.4-practice-large-sample-inference.html"><a href="6.4-practice-large-sample-inference.html"><i class="fa fa-check"></i><b>6.4</b> Practice: Large Sample Inference</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="6.4-practice-large-sample-inference.html"><a href="6.4-practice-large-sample-inference.html#normally-distributed-hatbeta-for-ntoinfty"><i class="fa fa-check"></i><b>6.4.1</b> Normally Distributed <span class="math inline">\(\hat\beta\)</span> for <span class="math inline">\(n\to\infty\)</span></a></li>
<li class="chapter" data-level="6.4.2" data-path="6.4-practice-large-sample-inference.html"><a href="6.4-practice-large-sample-inference.html#testing-multiple-and-single-parameters"><i class="fa fa-check"></i><b>6.4.2</b> Testing Multiple and Single Parameters</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="7-maximum-likelihood.html"><a href="7-maximum-likelihood.html"><i class="fa fa-check"></i><b>7</b> Maximum Likelihood</a>
<ul>
<li class="chapter" data-level="7.1" data-path="7.1-likelihood-principle.html"><a href="7.1-likelihood-principle.html"><i class="fa fa-check"></i><b>7.1</b> Likelihood Principle</a></li>
<li class="chapter" data-level="7.2" data-path="7.2-properties-of-maximum-likelihood-estimators.html"><a href="7.2-properties-of-maximum-likelihood-estimators.html"><i class="fa fa-check"></i><b>7.2</b> Properties of Maximum Likelihood Estimators</a></li>
<li class="chapter" data-level="7.3" data-path="7.3-the-log-likelihood-function.html"><a href="7.3-the-log-likelihood-function.html"><i class="fa fa-check"></i><b>7.3</b> The (Log-)Likelihood Function</a></li>
<li class="chapter" data-level="7.4" data-path="7.4-optimization-non-analytical-solutions.html"><a href="7.4-optimization-non-analytical-solutions.html"><i class="fa fa-check"></i><b>7.4</b> Optimization: Non-Analytical Solutions</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="7.4-optimization-non-analytical-solutions.html"><a href="7.4-optimization-non-analytical-solutions.html#newton-raphson-optimization"><i class="fa fa-check"></i><b>7.4.1</b> Newton-Raphson Optimization</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="7.5-ols-estimation-as-ml-estimation.html"><a href="7.5-ols-estimation-as-ml-estimation.html"><i class="fa fa-check"></i><b>7.5</b> OLS-Estimation as ML-Estimation</a></li>
<li class="chapter" data-level="7.6" data-path="7.6-variance-of-ml-estimators-hatbeta_ml-and-s2_ml.html"><a href="7.6-variance-of-ml-estimators-hatbeta_ml-and-s2_ml.html"><i class="fa fa-check"></i><b>7.6</b> Variance of ML-Estimators <span class="math inline">\(\hat\beta_{ML}\)</span> and <span class="math inline">\(s^2_{ML}\)</span></a></li>
<li class="chapter" data-level="7.7" data-path="7.7-consistency-of-hatbeta_ml-and-s_ml2.html"><a href="7.7-consistency-of-hatbeta_ml-and-s_ml2.html"><i class="fa fa-check"></i><b>7.7</b> Consistency of <span class="math inline">\(\hat\beta_{ML}\)</span> and <span class="math inline">\(s_{ML}^2\)</span></a></li>
<li class="chapter" data-level="7.8" data-path="7.8-asymptotic-theory-of-maximum-likelihood-estimators.html"><a href="7.8-asymptotic-theory-of-maximum-likelihood-estimators.html"><i class="fa fa-check"></i><b>7.8</b> Asymptotic Theory of Maximum-Likelihood Estimators</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="8-ivr.html"><a href="8-ivr.html"><i class="fa fa-check"></i><b>8</b> Instrumental Variables Regression</a>
<ul>
<li class="chapter" data-level="8.1" data-path="8.1-TIVEWASRAASI.html"><a href="8.1-TIVEWASRAASI.html"><i class="fa fa-check"></i><b>8.1</b> The IV Estimator with a Single Regressor and a Single Instrument</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="8.1-TIVEWASRAASI.html"><a href="8.1-TIVEWASRAASI.html#the-two-stage-least-squares-estimator"><i class="fa fa-check"></i><b>8.1.1</b> The Two-Stage Least Squares Estimator</a></li>
<li class="chapter" data-level="8.1.2" data-path="8.1-TIVEWASRAASI.html"><a href="8.1-TIVEWASRAASI.html#application-demand-for-cigarettes-12"><i class="fa fa-check"></i><b>8.1.2</b> Application: Demand For Cigarettes (1/2)</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="8.2-TGIVRM.html"><a href="8.2-TGIVRM.html"><i class="fa fa-check"></i><b>8.2</b> The General IV Regression Model</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="8.2-TGIVRM.html"><a href="8.2-TGIVRM.html#application-demand-for-cigarettes-22"><i class="fa fa-check"></i><b>8.2.1</b> Application: Demand for Cigarettes (2/2)</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="8.3-civ.html"><a href="8.3-civ.html"><i class="fa fa-check"></i><b>8.3</b> Checking Instrument Validity</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="8.3-civ.html"><a href="8.3-civ.html#instrument-relevance"><i class="fa fa-check"></i><b>8.3.1</b> Instrument Relevance</a></li>
<li class="chapter" data-level="8.3.2" data-path="8.3-civ.html"><a href="8.3-civ.html#instrument-validity"><i class="fa fa-check"></i><b>8.3.2</b> Instrument Validity</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="8.4-attdfc.html"><a href="8.4-attdfc.html"><i class="fa fa-check"></i><b>8.4</b> Application to the Demand for Cigarettes</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Econometrics (M.Sc.)</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="TIVEWASRAASI" class="section level2" number="8.1">
<h2><span class="header-section-number">8.1</span> The IV Estimator with a Single Regressor and a Single Instrument</h2>
<p>Consider the simple regression model
<span class="math display">\[\begin{align}
  Y_i = \beta_1 + \beta_2 X_i + \eps_i \ \ , \ \ i=1,\dots,n, \label{eq:srm12}
\end{align}\]</span>
where the error term <span class="math inline">\(\eps_i\)</span> is correlated with the regressor <span class="math inline">\(X_i\)</span> (<span class="math inline">\(X\)</span> is the called ). In this case Assumption 2 is violated, that is, strict exogeneity and orthogonality between <span class="math inline">\(X_i\)</span> and <span class="math inline">\(\eps_i\)</span> do not hold. Therefore, OLS estimation (also maximum likelihood and methods of moments estimation) is inconsistent for the true <span class="math inline">\(\beta_2\)</span>. In the most simple case, IV regression uses a single instrumental variable <span class="math inline">\(Z_i\)</span> to obtain a consistent estimator for <span class="math inline">\(\beta_2\)</span>.</p>
<span class="math inline">\(Z_i\)</span> must satisfy two conditions to be a valid instrument:
<div id="the-two-stage-least-squares-estimator" class="section level3" number="8.1.1">
<h3><span class="header-section-number">8.1.1</span> The Two-Stage Least Squares Estimator</h3>
<p>As can be guessed from its name, TSLS proceeds in two stages. In the first stage, the variation in the endogenous regressor <span class="math inline">\(X_i\)</span> is decomposed into a  component that is explained by the (exogenous) instrument <span class="math inline">\(Z_i\)</span> and a problematic component that is correlated with the error <span class="math inline">\(\eps_i\)</span>. The second stage uses the problem-free component of the variation in <span class="math inline">\(X_i\)</span> to estimate <span class="math inline">\(\beta_2\)</span>.</p>
<p>The first stage regression model is
<span class="math display">\[
X_i = \pi_0 + \pi_1 Z_i + \nu_i,
\]</span>
where <span class="math inline">\(\pi_0 + \pi_1 Z_i\)</span> is the component of <span class="math inline">\(X_i\)</span> that is explained by <span class="math inline">\(Z_i\)</span> while <span class="math inline">\(\nu_i\)</span> is the component (an error term) that cannot be explained by <span class="math inline">\(Z_i\)</span> and exhibits correlation with <span class="math inline">\(\eps_i\)</span>.</p>
<p>Using the OLS estimates <span class="math inline">\(\widehat{\pi}_0\)</span> and <span class="math inline">\(\widehat{\pi}_1\)</span> we obtain predicted values <span class="math inline">\(\widehat{X}_i=\hat\pi_0+\hat\pi_1 Z_i,\ i=1,\dots,n\)</span>. If <span class="math inline">\(Z_i\)</span> is a valid instrument, the <span class="math inline">\(\widehat{X}_i\)</span> are problem-free in the sense that <span class="math inline">\(\widehat{X}_i\)</span> is  in a regression of <span class="math inline">\(Y_i\)</span> on <span class="math inline">\(\widehat{X}_i\)</span> which is done in the second stage regression. The second stage produces <span class="math inline">\(\widehat{\beta}_1^{TSLS}\)</span> and <span class="math inline">\(\widehat{\beta}_2^{TSLS}\)</span>, the TSLS estimates of <span class="math inline">\(\beta_1\)</span> and <span class="math inline">\(\beta_2\)</span>.</p>
<p>For the case of a single instrument one can show that the TSLS estimator of <span class="math inline">\(\beta_2\)</span> is
<span class="math display">\[\begin{align}
\widehat{\beta}_2^{TSLS} = \frac{s_{ZY}}{s_{ZX}} = \frac{\frac{1}{n-1}\sum_{i=1}^n(Y_i - \overline{Y})(Z_i - \overline{Z})}{\frac{1}{n-1}\sum_{i=1}^n(X_i - \overline{X})(Z_i - \overline{Z})}, \label{eq:simpletsls}
\end{align}\]</span>
which is nothing but the ratio of the sample covariance between <span class="math inline">\(Z_i\)</span> and <span class="math inline">\(Y_i\)</span> to the sample covariance between <span class="math inline">\(Z_i\)</span> and <span class="math inline">\(X_i\)</span>.</p>
<p>The estimator in  is a consistent estimator for <span class="math inline">\(\beta_2\)</span> in  under the assumption that <span class="math inline">\(Z_i\)</span> is a valid instrument. The CLT implies that the distribution of <span class="math inline">\(\widehat{\beta}_2^{TSLS}\)</span> can be approximated by a normal distribution if the sample size <span class="math inline">\(n\)</span> is large. This allows us to use <span class="math inline">\(t\)</span>-statistics, <span class="math inline">\(F\)</span>-statistics, confidence intervals, etc.</p>
</div>
<div id="application-demand-for-cigarettes-12" class="section level3" number="8.1.2">
<h3><span class="header-section-number">8.1.2</span> Application: Demand For Cigarettes (1/2)</h3>
<p>The relation between the demand for and the price of commodities is a simple yet widespread problem in economics. Health economics is concerned with the study of how health-affecting behavior of individuals is influenced by the health-care system and regulation policy. Probably the most prominent example in public policy debates is smoking as it is related to many illnesses and negative externalities.</p>
<p>It is plausible that cigarette consumption can be reduced by taxing cigarettes more heavily. The question is by <em>how much</em> taxes must be increased to reach a certain reduction in cigarette consumption. Economists use elasticities to answer this kind of question. Since the price elasticity for the demand of cigarettes is unknown, it must be estimated. A simple OLS regression of log quantity on log price cannot be used to estimate the effect of interest since there is simultaneous causality between demand and supply. Instead, IV regression can be used.</p>
<p>We use the data set <code>CigarettesSW</code> which comes with the package <code>AER</code>. It is a panel data set that contains observations on cigarette consumption and several economic indicators for all 48 continental federal states of the U.S. from 1985 to 1995. In the following, however, we consider data for the cross section of states in 1995 only – that is, we transform the panel data to a cross-sectional data set. We start by loading the package, attaching the data set. An overview about summary statistics for each of the variables is returned by <code>summary(CigarettesSW)</code>. Use <code>?CigarettesSW</code> for a detailed description of the variables.</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="8.1-TIVEWASRAASI.html#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load the data set and get an overview</span></span>
<span id="cb98-2"><a href="8.1-TIVEWASRAASI.html#cb98-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;AER&quot;</span>)</span>
<span id="cb98-3"><a href="8.1-TIVEWASRAASI.html#cb98-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;CigarettesSW&quot;</span>)</span>
<span id="cb98-4"><a href="8.1-TIVEWASRAASI.html#cb98-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(CigarettesSW)</span></code></pre></div>
<pre><code>#&gt;      state      year         cpi          population           packs       
#&gt;  AL     : 2   1985:48   Min.   :1.076   Min.   :  478447   Min.   : 49.27  
#&gt;  AR     : 2   1995:48   1st Qu.:1.076   1st Qu.: 1622606   1st Qu.: 92.45  
#&gt;  AZ     : 2             Median :1.300   Median : 3697472   Median :110.16  
#&gt;  CA     : 2             Mean   :1.300   Mean   : 5168866   Mean   :109.18  
#&gt;  CO     : 2             3rd Qu.:1.524   3rd Qu.: 5901500   3rd Qu.:123.52  
#&gt;  CT     : 2             Max.   :1.524   Max.   :31493524   Max.   :197.99  
#&gt;  (Other):84                                                                
#&gt;      income               tax            price             taxs       
#&gt;  Min.   :  6887097   Min.   :18.00   Min.   : 84.97   Min.   : 21.27  
#&gt;  1st Qu.: 25520384   1st Qu.:31.00   1st Qu.:102.71   1st Qu.: 34.77  
#&gt;  Median : 61661644   Median :37.00   Median :137.72   Median : 41.05  
#&gt;  Mean   : 99878736   Mean   :42.68   Mean   :143.45   Mean   : 48.33  
#&gt;  3rd Qu.:127313964   3rd Qu.:50.88   3rd Qu.:176.15   3rd Qu.: 59.48  
#&gt;  Max.   :771470144   Max.   :99.00   Max.   :240.85   Max.   :112.63  
#&gt; </code></pre>
<p>We are interested in estimating <span class="math inline">\(\beta_2\)</span> in
<span class="math display">\[\begin{align}
  \log(Q_i^{cigarettes}) = \beta_1 + \beta_2 \log(P_i^{cigarettes}) + \eps_i, \label{eq:cigstsls}
\end{align}\]</span>
where <span class="math inline">\(Q_i^{cigarettes}\)</span> is the number of cigarette packs per capita sold and <span class="math inline">\(P_i^{cigarettes}\)</span> is the after-tax average real price per pack of cigarettes in state <span class="math inline">\(i=1,\dots,n=48\)</span>.</p>
The instrumental variable we are going to use for instrumenting the endogenous regressor <span class="math inline">\(\log(P_i^{cigarettes})\)</span> is <span class="math inline">\(SalesTax\)</span>, the portion of taxes on cigarettes arising from the general sales tax. <span class="math inline">\(SalesTax\)</span> is measured in dollars per pack. The idea is that:
<p>In the following, we perform some transformations in order to obtain deflated cross section data for the year 1995. We also compute the sample correlation between the sales tax and price per pack. The sample correlation is a consistent estimator of the population correlation. The estimate of approximately <span class="math inline">\(0.614\)</span> indicates that <span class="math inline">\(SalesTax\)</span> and <span class="math inline">\(P_i^{cigarettes}\)</span> exhibit positive correlation which meets our expectations: higher sales taxes lead to higher prices. However, a correlation analysis like this is not sufficient for checking whether the instrument is relevant. We will later come back to the issue of checking whether an instrument is relevant and exogenous; see Chapter <a href="8.3-civ.html#civ">8.3</a>.</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="8.1-TIVEWASRAASI.html#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute real per capita prices</span></span>
<span id="cb100-2"><a href="8.1-TIVEWASRAASI.html#cb100-2" aria-hidden="true" tabindex="-1"></a>CigarettesSW<span class="sc">$</span>rprice <span class="ot">&lt;-</span> <span class="fu">with</span>(CigarettesSW, price <span class="sc">/</span> cpi)</span>
<span id="cb100-3"><a href="8.1-TIVEWASRAASI.html#cb100-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-4"><a href="8.1-TIVEWASRAASI.html#cb100-4" aria-hidden="true" tabindex="-1"></a><span class="co">#  compute the sales tax</span></span>
<span id="cb100-5"><a href="8.1-TIVEWASRAASI.html#cb100-5" aria-hidden="true" tabindex="-1"></a>CigarettesSW<span class="sc">$</span>salestax <span class="ot">&lt;-</span> <span class="fu">with</span>(CigarettesSW, (taxs <span class="sc">-</span> tax) <span class="sc">/</span> cpi)</span>
<span id="cb100-6"><a href="8.1-TIVEWASRAASI.html#cb100-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-7"><a href="8.1-TIVEWASRAASI.html#cb100-7" aria-hidden="true" tabindex="-1"></a><span class="co"># check the correlation between sales tax and price</span></span>
<span id="cb100-8"><a href="8.1-TIVEWASRAASI.html#cb100-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(CigarettesSW<span class="sc">$</span>salestax, CigarettesSW<span class="sc">$</span>price)</span>
<span id="cb100-9"><a href="8.1-TIVEWASRAASI.html#cb100-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 0.6141228</span></span>
<span id="cb100-10"><a href="8.1-TIVEWASRAASI.html#cb100-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-11"><a href="8.1-TIVEWASRAASI.html#cb100-11" aria-hidden="true" tabindex="-1"></a><span class="co"># generate a subset for the year 1995</span></span>
<span id="cb100-12"><a href="8.1-TIVEWASRAASI.html#cb100-12" aria-hidden="true" tabindex="-1"></a>c1995 <span class="ot">&lt;-</span> <span class="fu">subset</span>(CigarettesSW, year <span class="sc">==</span> <span class="st">&quot;1995&quot;</span>)</span></code></pre></div>
<p>The first stage regression is
<span class="math display">\[
\log(P_i^{cigarettes}) = \pi_0 + \pi_1 SalesTax_i + \nu_i.
\]</span>
We estimate this model in  using <code>lm()</code>. In the second stage we run a regression of <span class="math inline">\(\log(Q_i^{cigarettes})\)</span> on <span class="math inline">\(\widehat{\log(P_i^{cigarettes})}\)</span> to obtain <span class="math inline">\(\widehat{\beta}_1^{TSLS}\)</span> and <span class="math inline">\(\widehat{\beta}_2^{TSLS}\)</span>.</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="8.1-TIVEWASRAASI.html#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="co"># perform the first stage regression</span></span>
<span id="cb101-2"><a href="8.1-TIVEWASRAASI.html#cb101-2" aria-hidden="true" tabindex="-1"></a>cig_s1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(rprice) <span class="sc">~</span> salestax, <span class="at">data =</span> c1995)</span>
<span id="cb101-3"><a href="8.1-TIVEWASRAASI.html#cb101-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-4"><a href="8.1-TIVEWASRAASI.html#cb101-4" aria-hidden="true" tabindex="-1"></a><span class="fu">coeftest</span>(cig_s1, <span class="at">vcov =</span> vcovHC, <span class="at">type =</span> <span class="st">&quot;HC1&quot;</span>)</span>
<span id="cb101-5"><a href="8.1-TIVEWASRAASI.html#cb101-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb101-6"><a href="8.1-TIVEWASRAASI.html#cb101-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; t test of coefficients:</span></span>
<span id="cb101-7"><a href="8.1-TIVEWASRAASI.html#cb101-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb101-8"><a href="8.1-TIVEWASRAASI.html#cb101-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;              Estimate Std. Error  t value  Pr(&gt;|t|)    </span></span>
<span id="cb101-9"><a href="8.1-TIVEWASRAASI.html#cb101-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; (Intercept) 4.6165463  0.0289177 159.6444 &lt; 2.2e-16 ***</span></span>
<span id="cb101-10"><a href="8.1-TIVEWASRAASI.html#cb101-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; salestax    0.0307289  0.0048354   6.3549 8.489e-08 ***</span></span>
<span id="cb101-11"><a href="8.1-TIVEWASRAASI.html#cb101-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; ---</span></span>
<span id="cb101-12"><a href="8.1-TIVEWASRAASI.html#cb101-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</span></span></code></pre></div>
<p>The first stage regression is
<span class="math display">\[
\widehat{\log(P_i^{cigarettes})} = \underset{(0.03)}{4.62} + \underset{(0.005)}{0.031}\; SalesTax_i
\]</span>
which predicts the relation between sales tax price per cigarettes to be positive. How much of the observed variation in <span class="math inline">\(\log(P^{cigarettes})\)</span> is explained by the instrument <span class="math inline">\(SalesTax\)</span>? This can be answered by looking at the regression’s <span class="math inline">\(R^2\)</span> which states that about <span class="math inline">\(47\%\)</span> of the variation in after tax prices is explained by the variation of the sales tax across states.</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="8.1-TIVEWASRAASI.html#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="co"># inspect the R^2 of the first stage regression</span></span>
<span id="cb102-2"><a href="8.1-TIVEWASRAASI.html#cb102-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cig_s1)<span class="sc">$</span>r.squared</span>
<span id="cb102-3"><a href="8.1-TIVEWASRAASI.html#cb102-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 0.4709961</span></span></code></pre></div>
<p>We next store <span class="math inline">\(\widehat{\log(P_i^{cigarettes})}\)</span>, the fitted values obtained by the first stage regression <code>cig_s1</code>, in the variable <code>lcigp_pred</code>.</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="8.1-TIVEWASRAASI.html#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="co"># store the predicted values</span></span>
<span id="cb103-2"><a href="8.1-TIVEWASRAASI.html#cb103-2" aria-hidden="true" tabindex="-1"></a>lcigp_pred <span class="ot">&lt;-</span> cig_s1<span class="sc">$</span>fitted.values</span></code></pre></div>
<p>Next, we run the second stage regression which gives us the TSLS estimates we seek.</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="8.1-TIVEWASRAASI.html#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="co"># run the stage 2 regression</span></span>
<span id="cb104-2"><a href="8.1-TIVEWASRAASI.html#cb104-2" aria-hidden="true" tabindex="-1"></a>cig_s2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(c1995<span class="sc">$</span>packs) <span class="sc">~</span> lcigp_pred)</span>
<span id="cb104-3"><a href="8.1-TIVEWASRAASI.html#cb104-3" aria-hidden="true" tabindex="-1"></a><span class="fu">coeftest</span>(cig_s2, <span class="at">vcov =</span> vcovHC, <span class="at">type =</span> <span class="st">&quot;HC1&quot;</span>)</span>
<span id="cb104-4"><a href="8.1-TIVEWASRAASI.html#cb104-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb104-5"><a href="8.1-TIVEWASRAASI.html#cb104-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; t test of coefficients:</span></span>
<span id="cb104-6"><a href="8.1-TIVEWASRAASI.html#cb104-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb104-7"><a href="8.1-TIVEWASRAASI.html#cb104-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;             Estimate Std. Error t value  Pr(&gt;|t|)    </span></span>
<span id="cb104-8"><a href="8.1-TIVEWASRAASI.html#cb104-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; (Intercept)   9.7199     1.5971  6.0859 2.153e-07 ***</span></span>
<span id="cb104-9"><a href="8.1-TIVEWASRAASI.html#cb104-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; lcigp_pred   -1.0836     0.3337 -3.2472  0.002178 ** </span></span>
<span id="cb104-10"><a href="8.1-TIVEWASRAASI.html#cb104-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; ---</span></span>
<span id="cb104-11"><a href="8.1-TIVEWASRAASI.html#cb104-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</span></span></code></pre></div>
<p>Thus estimating the model  using TSLS yields
<span class="math display">\[\begin{align}
  \widehat{\log(Q_i^{cigarettes})} = \underset{(1.60)}{9.72} - \underset{(0.33)}{1.08} \widehat{\log(P_i^{cigarettes})}, \label{eq:ecigstsls}
\end{align}\]</span></p>
<p>The function <code>ivreg()</code> from the package <code>AER</code> carries out TSLS procedure automatically. It is used similarly as <code>lm()</code>. Instruments can be added to the usual specification of the regression formula using a vertical bar separating the model equation from the instruments. Thus, for the regression at hand the correct formula is <code>log(packs) ~ log(rprice) | salestax</code>.</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="8.1-TIVEWASRAASI.html#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="co"># perform TSLS using &#39;ivreg()&#39;</span></span>
<span id="cb105-2"><a href="8.1-TIVEWASRAASI.html#cb105-2" aria-hidden="true" tabindex="-1"></a>cig_ivreg <span class="ot">&lt;-</span> <span class="fu">ivreg</span>(<span class="fu">log</span>(packs) <span class="sc">~</span> <span class="fu">log</span>(rprice) <span class="sc">|</span> salestax, </span>
<span id="cb105-3"><a href="8.1-TIVEWASRAASI.html#cb105-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> c1995)</span>
<span id="cb105-4"><a href="8.1-TIVEWASRAASI.html#cb105-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-5"><a href="8.1-TIVEWASRAASI.html#cb105-5" aria-hidden="true" tabindex="-1"></a><span class="fu">coeftest</span>(cig_ivreg, <span class="at">vcov =</span> vcovHC, <span class="at">type =</span> <span class="st">&quot;HC1&quot;</span>)</span>
<span id="cb105-6"><a href="8.1-TIVEWASRAASI.html#cb105-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb105-7"><a href="8.1-TIVEWASRAASI.html#cb105-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; t test of coefficients:</span></span>
<span id="cb105-8"><a href="8.1-TIVEWASRAASI.html#cb105-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb105-9"><a href="8.1-TIVEWASRAASI.html#cb105-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;             Estimate Std. Error t value  Pr(&gt;|t|)    </span></span>
<span id="cb105-10"><a href="8.1-TIVEWASRAASI.html#cb105-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; (Intercept)  9.71988    1.52832  6.3598 8.346e-08 ***</span></span>
<span id="cb105-11"><a href="8.1-TIVEWASRAASI.html#cb105-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; log(rprice) -1.08359    0.31892 -3.3977  0.001411 ** </span></span>
<span id="cb105-12"><a href="8.1-TIVEWASRAASI.html#cb105-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; ---</span></span>
<span id="cb105-13"><a href="8.1-TIVEWASRAASI.html#cb105-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</span></span></code></pre></div>
<p>We find that the coefficient estimates coincide for both approaches.</p>
<p>The TSLS estimate for <span class="math inline">\(\beta_2\)</span> in  suggests that an increase in cigarette prices by one percent reduces cigarette consumption by roughly <span class="math inline">\(1.08\)</span> percentage points, which is fairly elastic. However, we should keep in mind that this estimate might not be trustworthy even though we used IV estimation: there still might be a bias due to . Thus a multiple IV regression approach is needed to reduce the risk of omitted variable biases.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="8-ivr.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="8.2-TGIVRM.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "serif",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Script_Econometrics_MSc.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
